/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and their workspaces */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/harnesses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
            };
            cookie?: never;
        };
        /** The latest version of every harness, sorted by name */
        get: operations["listHarnesses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/harnesses/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                name: string;
            };
            cookie?: never;
        };
        /** The latest version of a harness */
        get: operations["getHarness"];
        /**
         * Store a harness as its next version
         * @description A changed harness becomes the next version; an unchanged one is left
         *     as it is, and its latest version is returned. The name must match
         *     the path.
         */
        put: operations["putHarness"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
            };
            cookie?: never;
        };
        /** The runs, newest first, a page at a time */
        get: operations["listRuns"];
        put?: never;
        /**
         * Start a run of a harness's latest version
         * @description Queues the run, which starts once a worker is free; its events tell
         *     when. A run whose MCP servers cannot serve its grants fails.
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** A run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs/{id}/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Continue a run's conversation with a new run
         * @description Starts a run of the harness version of the run it follows, not the
         *     latest, that continues the conversation: the model sees the earlier
         *     runs' transcripts, with secrets redacted, before the new input. Only the conversation's
         *     latest run can be followed up, once it has finished; any other is a
         *     conflict. A run that failed or was cancelled is continued from where
         *     it stopped: the model is told so, and that a tool call whose result
         *     was not recorded may or may not have run. No call is run again.
         */
        post: operations["followUpRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs/{id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** The runs of the conversation a run belongs to, oldest first */
        get: operations["getRunConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a queued, waiting or running run
         * @description A queued run, or one waiting for approval, ends at once; a running
         *     one as soon as what it is doing stops. Either ends as cancelled by
         *     the user; its events tell when.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** A run's audit records, in the order they were recorded */
        get: operations["getRunAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** A run's conversation with the model, with secrets redacted */
        get: operations["getRunTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /**
         * A run's events, as server-sent events
         * @description The events from the run's start. A running run's stream follows it
         *     until it finishes; a finished run's stream replays its audit records
         *     and its end. Each event's data is JSON:
         *
         *     - `audit`: an AuditRecord
         *     - `approval`: an ApprovalRequest
         *     - `finished`: the Run, always the last event
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/runs/{id}/approvals/{approval}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
                approval: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer an approval request
         * @description The signed-in user is recorded as the approver. The answer queues the
         *     run, which resumes at the call; a request is answered once, and not
         *     after it expired, which rejected it.
         */
        post: operations["answerApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
            };
            cookie?: never;
        };
        /** The approval requests waiting for an answer, oldest first */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Me: {
            user: string;
            /** @description The workspaces the user is a member of, sorted. */
            workspaces: string[];
        };
        /** @description A declarative definition of an agent. */
        Harness: {
            name: string;
            instructions: string;
            model: components["schemas"]["HarnessModel"];
            /** @description The granted tools. */
            tools?: string[];
            limits: components["schemas"]["Limits"];
            /**
             * @description Rego modules in package agenty.tool that tighten central policy
             *     for this harness.
             */
            policy?: components["schemas"]["PolicyModule"][];
        };
        HarnessModel: {
            provider: string;
            name: string;
        };
        Limits: {
            /** @description Bounds the model calls of a run. */
            max_steps: number;
            /** @description Bounds the tool calls of a run, denied ones included. */
            max_tool_calls: number;
        };
        PolicyModule: {
            name: string;
            source: string;
        };
        HarnessVersion: {
            /**
             * Format: int64
             * @description Identifies the version across all harnesses.
             */
            id: number;
            version: number;
            harness: components["schemas"]["Harness"];
            /** Format: date-time */
            created_at: string;
        };
        CreateRun: {
            /** @description The harness to run, by name; the run uses its latest version. */
            harness: string;
            input: string;
        };
        FollowUp: {
            input: string;
        };
        /** @enum {string} */
        RunStatus: "queued" | "running" | "waiting" | "succeeded" | "failed" | "cancelled";
        Run: {
            id: string;
            /**
             * @description The conversation the run belongs to, named by the ID of its
             *     first run, which may be this one.
             */
            conversation_id: string;
            /** @description The run whose conversation this run continues, if any. */
            follows?: string;
            /** Format: int64 */
            harness_version_id: number;
            harness: string;
            harness_version: number;
            /** @description The user who started the run. */
            started_by: string;
            input: string;
            status: components["schemas"]["RunStatus"];
            output: string;
            steps: number;
            /**
             * @description The tokens of the model calls that wrote the run's replies so
             *     far. A call that failed, such as one whose reply was cut off, is
             *     not counted.
             */
            usage: components["schemas"]["Usage"];
            /** @description Why the run failed, or who cancelled it. */
            error?: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Unset until the run has finished.
             */
            finished_at?: string;
        };
        /**
         * @description The tokens of model calls. Input the provider read from its prompt
         *     cache, or wrote to it, is counted apart from the rest of the input.
         */
        Usage: {
            /**
             * Format: int64
             * @description Input tokens neither read from nor written to the cache.
             */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /**
             * Format: int64
             * @description Input tokens written to the prompt cache.
             */
            cache_write_tokens: number;
            /**
             * Format: int64
             * @description Input tokens read from the prompt cache.
             */
            cache_read_tokens: number;
        };
        RunList: {
            runs: components["schemas"]["Run"][];
            /** @description The before parameter of the next page, which may be empty. */
            next?: string;
        };
        /** @enum {string} */
        AuditEvent: "decision" | "approval" | "result";
        /** @enum {string} */
        Decision: "allow" | "deny" | "require_approval";
        /** @description One decision, approval or result the tool gateway recorded. */
        AuditRecord: {
            run_id: string;
            call_id: string;
            event: components["schemas"]["AuditEvent"];
            tool: string;
            args?: components["schemas"]["JSON"];
            decision: components["schemas"]["Decision"];
            reason?: string;
            /** @description Who approved or rejected the call, if anyone did. */
            approver?: string;
            result?: components["schemas"]["JSON"];
            error?: string;
            /** Format: date-time */
            recorded_at: string;
        };
        /** @enum {string} */
        Role: "user" | "assistant";
        ToolCall: {
            id: string;
            name: string;
            args?: components["schemas"]["JSON"];
        };
        ToolResult: {
            call_id: string;
            content: string;
            is_error?: boolean;
        };
        /**
         * @description A message in the form of the provider that generated it, kept so it
         *     can be sent to the model again.
         */
        ProviderPart: {
            name: string;
            data: components["schemas"]["JSON"];
        };
        /**
         * @description One message of a run's conversation with the model: the input, a
         *     model reply, or the results of the reply's tool calls.
         */
        TranscriptMessage: {
            /** @description The message's index in the conversation. */
            position: number;
            role: components["schemas"]["Role"];
            text?: string;
            tool_calls?: components["schemas"]["ToolCall"][];
            tool_results?: components["schemas"]["ToolResult"][];
            provider?: components["schemas"]["ProviderPart"];
            /** @description The tokens of the model call that wrote a reply. */
            usage?: components["schemas"]["Usage"];
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description A call that policy marked as requiring approval. Secrets are already
         *     redacted from it.
         */
        ApprovalRequest: {
            /** @description Identifies the request when answering it. */
            id: string;
            run_id: string;
            harness: string;
            tool: string;
            args: components["schemas"]["JSON"];
            reasons: string[];
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description When the request is rejected if no one answers it.
             */
            expires_at: string;
        };
        Answer: {
            approved: boolean;
            reason?: string;
        };
        /** @description Any JSON value, kept as written. */
        JSON: unknown;
    };
    responses: {
        /** @description An error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Workspace: string;
        RunID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listHarnesses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The harnesses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarnessVersion"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getHarness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The harness version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarnessVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    putHarness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Harness"];
            };
        };
        responses: {
            /** @description The stored version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarnessVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Only the runs of this harness. */
                harness?: string;
                /** @description Only the runs with this status. */
                status?: components["schemas"]["RunStatus"];
                /** @description The page size. */
                limit?: number;
                /**
                 * @description Continue after the run with this ID, as RunList.next gives it. A
                 *     run that is not one of the workspace's gives an empty page.
                 */
                before?: string;
            };
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRun"];
            };
        };
        responses: {
            /** @description The run, queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    followUpRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUp"];
            };
        };
        responses: {
            /** @description The run, queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRunConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run is being cancelled. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getRunAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The audit records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecord"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRunTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The messages, in order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptMessage"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    answerApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
                id: components["parameters"]["RunID"];
                approval: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Answer"];
            };
        };
        responses: {
            /** @description The answer is accepted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listApprovals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace: components["parameters"]["Workspace"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
