// The Better Auth options that shape the database schema, shared by createAuth (auth.ts) and
// scripts/auth-generate.config.ts, from which `task auth:generate` writes src/server/db/auth-schema.ts.
// No "server-only" import and only package imports: the Better Auth CLI loads this in plain Node.
import type { BetterAuthPlugin } from "better-auth";

/** `advanced.database`: uuid primary keys, generated by Postgres (gen_random_uuid). */
export const databaseOptions = { generateId: "uuid" } as const;

/** The sso plugin's `schema` option: our provider columns. */
export const ssoSchema = {
  ssoProvider: {
    additionalFields: {
      // How the ID token maps to an organization and a role.
      organizationClaim: { type: "string", required: true },
      roleClaim: { type: "string", required: false },
      adminValues: { type: "string", required: false }, // comma-separated
    },
  },
} as const;

/**
 * Declares our organization and member tables so Better Auth's adapter can read and write them,
 * and makes sso_provider.user_id nullable: providers are registered by operators (seed or SQL), not
 * by a user. The sso plugin rejects `userId` in additionalFields, but Better Auth merges the plugins'
 * fields per table with later plugins winning, so this plugin must come after sso().
 */
export const organizationsPlugin = {
  id: "agenty-organizations",
  schema: {
    ssoProvider: {
      fields: {
        userId: {
          type: "string",
          required: false,
          references: { model: "user", field: "id", onDelete: "cascade" },
        },
      },
    },
    organization: {
      fields: {
        slug: { type: "string", required: true, unique: true },
        providerId: {
          type: "string",
          required: false,
          references: { model: "ssoProvider", field: "providerId", onDelete: "set null" },
        },
        createdAt: { type: "date", required: true, defaultValue: () => new Date() },
        updatedAt: { type: "date", required: true, defaultValue: () => new Date() },
      },
    },
    member: {
      fields: {
        // One organization per user.
        userId: {
          type: "string",
          required: true,
          unique: true,
          references: { model: "user", field: "id", onDelete: "cascade" },
        },
        organizationId: {
          type: "string",
          required: true,
          index: true,
          references: { model: "organization", field: "id", onDelete: "cascade" },
        },
        role: { type: "string", required: true },
        createdAt: { type: "date", required: true, defaultValue: () => new Date() },
        updatedAt: { type: "date", required: true, defaultValue: () => new Date() },
      },
    },
  },
} satisfies BetterAuthPlugin;
