// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package server

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	. "github.com/jangraefen/agenty/internal/api"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAuditEvents Every event of the audit log, newest first, a page at a time, for auditors
	// (GET /v1/audit/events)
	ListAuditEvents(c *gin.Context, params ListAuditEventsParams)
	// ExportAuditLog The audit log as JSON lines, for auditors
	// (GET /v1/audit/export)
	ExportAuditLog(c *gin.Context, params ExportAuditLogParams)
	// ListAuditRuns The runs of every workspace, newest first, a page at a time, for auditors
	// (GET /v1/audit/runs)
	ListAuditRuns(c *gin.Context, params ListAuditRunsParams)
	// GetAuditRun A run of any workspace with its audit records, for auditors
	// (GET /v1/audit/runs/{id})
	GetAuditRun(c *gin.Context, id string)
	// ListConversations The conversations the user started, latest activity first, a page at a time
	// (GET /v1/conversations)
	ListConversations(c *gin.Context, params ListConversationsParams)
	// GetConversation A conversation the user started, in one of their workspaces
	// (GET /v1/conversations/{id})
	GetConversation(c *gin.Context, id string)
	// GetMe The signed-in user and their workspaces
	// (GET /v1/me)
	GetMe(c *gin.Context)
	// ListMyActivity What the user did, newest first, a page at a time
	// (GET /v1/me/activity)
	ListMyActivity(c *gin.Context, params ListMyActivityParams)
	// ListApprovals The approval requests the user's own runs wait for, oldest first
	// (GET /v1/workspaces/{workspace}/approvals)
	ListApprovals(c *gin.Context, workspace Workspace)
	// ListWorkspaceAuditEvents The changes made to a workspace, newest first, a page at a time
	// (GET /v1/workspaces/{workspace}/audit)
	ListWorkspaceAuditEvents(c *gin.Context, workspace Workspace, params ListWorkspaceAuditEventsParams)
	// ListHarnesses The latest version of every harness, sorted by name
	// (GET /v1/workspaces/{workspace}/harnesses)
	ListHarnesses(c *gin.Context, workspace Workspace)
	// GetHarness The latest version of a harness
	// (GET /v1/workspaces/{workspace}/harnesses/{name})
	GetHarness(c *gin.Context, workspace Workspace, name string)
	// PutHarness Store a harness as its next version
	// (PUT /v1/workspaces/{workspace}/harnesses/{name})
	PutHarness(c *gin.Context, workspace Workspace, name string)
	// CreateRun Start a run of a harness's latest version
	// (POST /v1/workspaces/{workspace}/runs)
	CreateRun(c *gin.Context, workspace Workspace)
	// GetRun A run
	// (GET /v1/workspaces/{workspace}/runs/{id})
	GetRun(c *gin.Context, workspace Workspace, id RunID)
	// AnswerApproval Answer an approval request
	// (POST /v1/workspaces/{workspace}/runs/{id}/approvals/{approval})
	AnswerApproval(c *gin.Context, workspace Workspace, id RunID, approval string)
	// CancelRun Cancel a queued, waiting or running run
	// (POST /v1/workspaces/{workspace}/runs/{id}/cancel)
	CancelRun(c *gin.Context, workspace Workspace, id RunID)
	// GetRunConversation The runs of the conversation a run belongs to, oldest first
	// (GET /v1/workspaces/{workspace}/runs/{id}/conversation)
	GetRunConversation(c *gin.Context, workspace Workspace, id RunID)
	// StreamRunEvents A run's events, as server-sent events
	// (GET /v1/workspaces/{workspace}/runs/{id}/events)
	StreamRunEvents(c *gin.Context, workspace Workspace, id RunID)
	// FollowUpRun Continue a run's conversation with a new run
	// (POST /v1/workspaces/{workspace}/runs/{id}/follow-up)
	FollowUpRun(c *gin.Context, workspace Workspace, id RunID)
	// GetRunTranscript A run's conversation with the model, with secrets redacted
	// (GET /v1/workspaces/{workspace}/runs/{id}/transcript)
	GetRunTranscript(c *gin.Context, workspace Workspace, id RunID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAuditEvents(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEventsParams

	// ------------- Optional query parameter "actor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor", c.Request.URL.Query(), &params.Actor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter actor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "workspace" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace", c.Request.URL.Query(), &params.Workspace, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", c.Request.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter action: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "run" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "run", c.Request.URL.Query(), &params.Run, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter run: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", c.Request.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter before: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAuditEvents(c, params)
}

// ExportAuditLog operation middleware
func (siw *ServerInterfaceWrapper) ExportAuditLog(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportAuditLogParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", c.Request.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter after: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportAuditLog(c, params)
}

// ListAuditRuns operation middleware
func (siw *ServerInterfaceWrapper) ListAuditRuns(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditRunsParams

	// ------------- Optional query parameter "workspace" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace", c.Request.URL.Query(), &params.Workspace, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "harness" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "harness", c.Request.URL.Query(), &params.Harness, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter harness: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "started_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "started_by", c.Request.URL.Query(), &params.StartedBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter started_by: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", c.Request.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter before: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAuditRuns(c, params)
}

// GetAuditRun operation middleware
func (siw *ServerInterfaceWrapper) GetAuditRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuditRun(c, id)
}

// ListConversations operation middleware
func (siw *ServerInterfaceWrapper) ListConversations(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConversationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", c.Request.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter before: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConversations(c, params)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConversation(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListMyActivity operation middleware
func (siw *ServerInterfaceWrapper) ListMyActivity(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMyActivityParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", c.Request.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter before: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyActivity(c, params)
}

// ListApprovals operation middleware
func (siw *ServerInterfaceWrapper) ListApprovals(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApprovals(c, workspace)
}

// ListWorkspaceAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ListWorkspaceAuditEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkspaceAuditEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", c.Request.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter before: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListWorkspaceAuditEvents(c, workspace, params)
}

// ListHarnesses operation middleware
func (siw *ServerInterfaceWrapper) ListHarnesses(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListHarnesses(c, workspace)
}

// GetHarness operation middleware
func (siw *ServerInterfaceWrapper) GetHarness(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHarness(c, workspace, name)
}

// PutHarness operation middleware
func (siw *ServerInterfaceWrapper) PutHarness(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutHarness(c, workspace, name)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRun(c, workspace)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRun(c, workspace, id)
}

// AnswerApproval operation middleware
func (siw *ServerInterfaceWrapper) AnswerApproval(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "approval" -------------
	var approval string

	err = runtime.BindStyledParameterWithOptions("simple", "approval", c.Param("approval"), &approval, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter approval: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AnswerApproval(c, workspace, id, approval)
}

// CancelRun operation middleware
func (siw *ServerInterfaceWrapper) CancelRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelRun(c, workspace, id)
}

// GetRunConversation operation middleware
func (siw *ServerInterfaceWrapper) GetRunConversation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRunConversation(c, workspace, id)
}

// StreamRunEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamRunEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StreamRunEvents(c, workspace, id)
}

// FollowUpRun operation middleware
func (siw *ServerInterfaceWrapper) FollowUpRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FollowUpRun(c, workspace, id)
}

// GetRunTranscript operation middleware
func (siw *ServerInterfaceWrapper) GetRunTranscript(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace Workspace

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", c.Param("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRunTranscript(c, workspace, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/v1/conversations", wrapper.ListConversations)
	router.GET(options.BaseURL+"/v1/conversations/:id", wrapper.GetConversation)
	router.GET(options.BaseURL+"/v1/audit/runs", wrapper.ListAuditRuns)
	router.GET(options.BaseURL+"/v1/audit/runs/:id", wrapper.GetAuditRun)
	router.GET(options.BaseURL+"/v1/me/activity", wrapper.ListMyActivity)
	router.GET(options.BaseURL+"/v1/audit/events", wrapper.ListAuditEvents)
	router.GET(options.BaseURL+"/v1/audit/export", wrapper.ExportAuditLog)
	router.GET(options.BaseURL+"/v1/workspaces/:workspace/audit", wrapper.ListWorkspaceAuditEvents)
	router.GET(options.BaseURL+"/v1/workspaces/:workspace/harnesses", wrapper.ListHarnesses)
	router.GET(options.BaseURL+"/v1/workspaces/:workspace/harnesses/:name", wrapper.GetHarness)
	router.PUT(options.BaseURL+"/v1/workspaces/:workspace/harnesses/:name", wrapper.PutHarness)
	router.POST(options.BaseURL+"/v1/workspaces/:workspace/runs", wrapper.CreateRun)
	router.GET(options.BaseURL+"/v1/workspaces/:workspace/runs/:id", wrapper.GetRun)
	router.POST(options.BaseURL+"/v1/workspaces/:workspace/runs/:id/follow-up", wrapper.FollowUpRun)
	router.GET(options.BaseURL+"/v1/workspaces/:workspace/runs/:id/conversation", wrapper.GetRunConversation)
	router.POST(options.BaseURL+"/v1/workspaces/:workspace/runs/:id/cancel", wrapper.CancelRun)
	router.GET(options.BaseURL+"/v1/workspaces/:workspace/runs/:id/transcript", wrapper.GetRunTranscript)
	router.GET(options.BaseURL+"/v1/workspaces/:workspace/runs/:id/events", wrapper.StreamRunEvents)
	router.POST(options.BaseURL+"/v1/workspaces/:workspace/runs/:id/approvals/:approval", wrapper.AnswerApproval)
	router.GET(options.BaseURL+"/v1/workspaces/:workspace/approvals", wrapper.ListApprovals)
}
