// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/jangraefen/agenty/internal/auditlog"
)

// Defines values for AuditEvent.
const (
	AuditEventApproval AuditEvent = "approval"
	AuditEventDecision AuditEvent = "decision"
	AuditEventResult   AuditEvent = "result"
)

// Valid indicates whether the value is a known member of the AuditEvent enum.
func (e AuditEvent) Valid() bool {
	switch e {
	case AuditEventApproval:
		return true
	case AuditEventDecision:
		return true
	case AuditEventResult:
		return true
	default:
		return false
	}
}

// Defines values for Decision.
const (
	DecisionAllow           Decision = "allow"
	DecisionDeny            Decision = "deny"
	DecisionRequireApproval Decision = "require_approval"
)

// Valid indicates whether the value is a known member of the Decision enum.
func (e Decision) Valid() bool {
	switch e {
	case DecisionAllow:
		return true
	case DecisionDeny:
		return true
	case DecisionRequireApproval:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAssistant Role = "assistant"
	RoleUser      Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAssistant:
		return true
	case RoleUser:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusCancelled RunStatus = "cancelled"
	RunStatusFailed    RunStatus = "failed"
	RunStatusQueued    RunStatus = "queued"
	RunStatusRunning   RunStatus = "running"
	RunStatusSucceeded RunStatus = "succeeded"
	RunStatusWaiting   RunStatus = "waiting"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusCancelled:
		return true
	case RunStatusFailed:
		return true
	case RunStatusQueued:
		return true
	case RunStatusRunning:
		return true
	case RunStatusSucceeded:
		return true
	case RunStatusWaiting:
		return true
	default:
		return false
	}
}

// Answer defines model for Answer.
type Answer struct {
	Approved bool   `json:"approved"`
	Reason   string `json:"reason,omitempty"`
}

// ApprovalRequest A call that policy marked as requiring approval. Secrets are already
// redacted from it.
type ApprovalRequest struct {
	// Args Any JSON value, kept as written.
	Args      JSON      `json:"args"`
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt When the request is rejected if no one answers it.
	ExpiresAt time.Time `json:"expires_at"`
	Harness   string    `json:"harness"`

	// ID Identifies the request when answering it.
	ID      string   `json:"id"`
	Reasons []string `json:"reasons"`
	RunID   string   `json:"run_id"`
	Tool    string   `json:"tool"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent string

// AuditLogEvent One event of the audit log, as package auditlog hashes it: hash is
// the SHA-256 of a fixed encoding of the other fields, prev_hash the
// hash of the event before it, zero before the first.
type AuditLogEvent = auditlog.Event

// AuditLogEventList defines model for AuditLogEventList.
type AuditLogEventList struct {
	Events []AuditLogEvent `json:"events"`

	// Next The before parameter of the next page; unset on the last.
	Next int64 `json:"next,omitempty"`
}

// AuditRecord One decision, approval or result the tool gateway recorded.
type AuditRecord struct {
	// Approver Who approved or rejected the call, if anyone did.
	Approver string `json:"approver,omitempty"`

	// Args Any JSON value, kept as written.
	Args       JSON       `json:"args,omitempty"`
	CallID     string     `json:"call_id"`
	Decision   Decision   `json:"decision"`
	Error      string     `json:"error,omitempty"`
	Event      AuditEvent `json:"event"`
	Reason     string     `json:"reason,omitempty"`
	RecordedAt time.Time  `json:"recorded_at"`

	// Result Any JSON value, kept as written.
	Result JSON   `json:"result,omitempty"`
	Tool   string `json:"tool"`
}

// AuditRun A run as auditors see it, without what was said in it.
type AuditRun struct {
	CreatedAt time.Time `json:"created_at"`

	// Error Why the run failed, or who cancelled it.
	Error string `json:"error,omitempty"`

	// FinishedAt Unset until the run has finished.
	FinishedAt     time.Time `json:"finished_at,omitempty,omitzero"`
	Follows        string    `json:"follows,omitempty"`
	Harness        string    `json:"harness"`
	HarnessVersion int       `json:"harness_version"`
	ID             string    `json:"id"`
	StartedBy      string    `json:"started_by"`
	Status         RunStatus `json:"status"`
	Steps          int       `json:"steps"`

	// Usage The tokens of model calls. Input the provider read from its prompt
	// cache, or wrote to it, is counted apart from the rest of the input.
	Usage     Usage  `json:"usage"`
	Workspace string `json:"workspace"`
}

// AuditRunDetail defines model for AuditRunDetail.
type AuditRunDetail struct {
	Records []AuditRecord `json:"records"`

	// Run A run as auditors see it, without what was said in it.
	Run AuditRun `json:"run"`
}

// AuditRunList defines model for AuditRunList.
type AuditRunList struct {
	// Next The before parameter of the next page, which may be empty.
	Next string     `json:"next,omitempty"`
	Runs []AuditRun `json:"runs"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	Harness string `json:"harness"`

	// ID The ID of the conversation's first run, which names it.
	ID string `json:"id"`

	// Runs The conversation's runs, oldest first.
	Runs []Run `json:"runs"`

	// Status The status of the conversation's latest run.
	Status RunStatus `json:"status"`

	// Title The first run's input, cut to its first 100 characters.
	Title     string `json:"title"`
	Workspace string `json:"workspace"`
}

// ConversationList defines model for ConversationList.
type ConversationList struct {
	Conversations []ConversationSummary `json:"conversations"`

	// Next The before parameter of the next page, which may be empty.
	Next string `json:"next,omitempty"`
}

// ConversationSummary defines model for ConversationSummary.
type ConversationSummary struct {
	Harness string `json:"harness"`

	// ID The ID of the conversation's first run, which names it.
	ID string `json:"id"`

	// Status The status of the conversation's latest run.
	Status RunStatus `json:"status"`

	// Title The first run's input, cut to its first 100 characters.
	Title     string `json:"title"`
	Workspace string `json:"workspace"`
}

// CreateRun defines model for CreateRun.
type CreateRun struct {
	// Harness The harness to run, by name; the run uses its latest version.
	Harness string `json:"harness"`
	Input   string `json:"input"`
}

// Decision defines model for Decision.
type Decision string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// FollowUp defines model for FollowUp.
type FollowUp struct {
	Input string `json:"input"`
}

// Harness A declarative definition of an agent.
type Harness struct {
	Instructions string       `json:"instructions"`
	Limits       Limits       `json:"limits"`
	Model        HarnessModel `json:"model"`
	Name         string       `json:"name"`

	// Policy Rego modules in package agenty.tool that tighten central policy
	// for this harness.
	Policy []PolicyModule `json:"policy,omitempty"`

	// Tools The granted tools.
	Tools []string `json:"tools,omitempty"`
}

// HarnessModel defines model for HarnessModel.
type HarnessModel struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
}

// HarnessVersion defines model for HarnessVersion.
type HarnessVersion struct {
	CreatedAt time.Time `json:"created_at"`

	// Harness A declarative definition of an agent.
	Harness Harness `json:"harness"`
	Version int     `json:"version"`
}

// JSON Any JSON value, kept as written.
type JSON = json.RawMessage

// Limits defines model for Limits.
type Limits struct {
	// MaxSteps Bounds the model calls of a run.
	MaxSteps int `json:"max_steps"`

	// MaxToolCalls Bounds the tool calls of a run, denied ones included.
	MaxToolCalls int `json:"max_tool_calls"`
}

// Me defines model for Me.
type Me struct {
	// Auditor Whether the user may read the audit log of every workspace.
	Auditor bool   `json:"auditor"`
	User    string `json:"user"`

	// Workspaces The workspaces the user is a member of, sorted.
	Workspaces []string `json:"workspaces"`
}

// PolicyModule defines model for PolicyModule.
type PolicyModule struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

// Role defines model for Role.
type Role string

// Run defines model for Run.
type Run struct {
	// ConversationID The conversation the run belongs to, named by the ID of its
	// first run, which may be this one.
	ConversationID string    `json:"conversation_id"`
	CreatedAt      time.Time `json:"created_at"`

	// Error Why the run failed, or who cancelled it.
	Error string `json:"error,omitempty"`

	// FinishedAt Unset until the run has finished.
	FinishedAt time.Time `json:"finished_at,omitempty,omitzero"`

	// Follows The run whose conversation this run continues, if any.
	Follows        string `json:"follows,omitempty"`
	Harness        string `json:"harness"`
	HarnessVersion int    `json:"harness_version"`
	ID             string `json:"id"`
	Input          string `json:"input"`
	Output         string `json:"output"`

	// StartedBy The user who started the run.
	StartedBy string    `json:"started_by"`
	Status    RunStatus `json:"status"`
	Steps     int       `json:"steps"`

	// Usage The tokens of the model calls that wrote the run's replies so
	// far. A call that failed, such as one whose reply was cut off, is
	// not counted.
	Usage Usage `json:"usage"`
}

// RunStatus defines model for RunStatus.
type RunStatus string

// ToolCall defines model for ToolCall.
type ToolCall struct {
	// Args Any JSON value, kept as written.
	Args JSON   `json:"args,omitempty"`
	ID   string `json:"id"`
	Name string `json:"name"`
}

// ToolResult defines model for ToolResult.
type ToolResult struct {
	CallID  string `json:"call_id"`
	Content string `json:"content"`
	IsError bool   `json:"is_error,omitempty"`
}

// TranscriptMessage One message of a run's conversation with the model: the input, a
// model reply, or the results of the reply's tool calls. What the
// provider kept of a reply for the model, such as its thinking, is
// not part of it.
type TranscriptMessage struct {
	// Position The message's index in the conversation.
	Position    int          `json:"position"`
	Role        Role         `json:"role"`
	Text        string       `json:"text,omitempty"`
	ToolCalls   []ToolCall   `json:"tool_calls,omitempty"`
	ToolResults []ToolResult `json:"tool_results,omitempty"`
}

// Usage The tokens of model calls. Input the provider read from its prompt
// cache, or wrote to it, is counted apart from the rest of the input.
type Usage struct {
	// CacheReadTokens Input tokens read from the prompt cache.
	CacheReadTokens int64 `json:"cache_read_tokens"`

	// CacheWriteTokens Input tokens written to the prompt cache.
	CacheWriteTokens int64 `json:"cache_write_tokens"`

	// InputTokens Input tokens neither read from nor written to the cache.
	InputTokens  int64 `json:"input_tokens"`
	OutputTokens int64 `json:"output_tokens"`
}

// WorkspaceDetail A workspace, as its members see it.
type WorkspaceDetail struct {
	// Members The users who are members of it, sorted.
	Members []string `json:"members"`
	Name    string   `json:"name"`
}

// BeforeEvent defines model for BeforeEvent.
type BeforeEvent = int64

// Limit defines model for Limit.
type Limit = int

// RunID defines model for RunID.
type RunID = string

// Workspace defines model for Workspace.
type Workspace = string

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	// Actor Only the events by this user.
	Actor string `form:"actor,omitempty" json:"actor,omitempty"`

	// Workspace Only the events in this workspace.
	Workspace string `form:"workspace,omitempty" json:"workspace,omitempty"`

	// Action Only the events with this action.
	Action string `form:"action,omitempty" json:"action,omitempty"`

	// Run Only the events about this run.
	Run string `form:"run,omitempty" json:"run,omitempty"`

	// Limit The page size.
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Continue before the event with this id, as AuditLogEventList.next
	// gives it; 0, the default, starts at the newest.
	Before BeforeEvent `form:"before,omitempty" json:"before,omitempty"`
}

// ExportAuditLogParams defines parameters for ExportAuditLog.
type ExportAuditLogParams struct {
	// After Start after the event with this id; 0, the default, starts at the first.
	After int64 `form:"after,omitempty" json:"after,omitempty"`
}

// ListAuditRunsParams defines parameters for ListAuditRuns.
type ListAuditRunsParams struct {
	// Workspace Only the runs of this workspace.
	Workspace string `form:"workspace,omitempty" json:"workspace,omitempty"`

	// Harness Only the runs of harnesses with this name.
	Harness string `form:"harness,omitempty" json:"harness,omitempty"`

	// StartedBy Only the runs this user started.
	StartedBy string `form:"started_by,omitempty" json:"started_by,omitempty"`

	// Status Only the runs with this status.
	Status RunStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit The page size.
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Continue after the run with this ID, as AuditRunList.next gives
	// it. A run that does not exist gives an empty page.
	Before string `form:"before,omitempty" json:"before,omitempty"`
}

// ListConversationsParams defines parameters for ListConversations.
type ListConversationsParams struct {
	// Limit The page size.
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Continue after the conversation this cursor names, as ConversationList.next gives it.
	Before string `form:"before,omitempty" json:"before,omitempty"`
}

// ListMyActivityParams defines parameters for ListMyActivity.
type ListMyActivityParams struct {
	// Limit The page size.
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Continue before the event with this id, as AuditLogEventList.next
	// gives it; 0, the default, starts at the newest.
	Before BeforeEvent `form:"before,omitempty" json:"before,omitempty"`
}

// ListWorkspaceAuditEventsParams defines parameters for ListWorkspaceAuditEvents.
type ListWorkspaceAuditEventsParams struct {
	// Limit The page size.
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Continue before the event with this id, as AuditLogEventList.next
	// gives it; 0, the default, starts at the newest.
	Before BeforeEvent `form:"before,omitempty" json:"before,omitempty"`
}

// PutHarnessJSONRequestBody defines body for PutHarness for application/json ContentType.
type PutHarnessJSONRequestBody = Harness

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRun

// AnswerApprovalJSONRequestBody defines body for AnswerApproval for application/json ContentType.
type AnswerApprovalJSONRequestBody = Answer

// FollowUpRunJSONRequestBody defines body for FollowUpRun for application/json ContentType.
type FollowUpRunJSONRequestBody = FollowUp
