// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"
)

// Defines values for AuditEvent.
const (
	AuditEventApproval AuditEvent = "approval"
	AuditEventDecision AuditEvent = "decision"
	AuditEventResult   AuditEvent = "result"
)

// Valid indicates whether the value is a known member of the AuditEvent enum.
func (e AuditEvent) Valid() bool {
	switch e {
	case AuditEventApproval:
		return true
	case AuditEventDecision:
		return true
	case AuditEventResult:
		return true
	default:
		return false
	}
}

// Defines values for Decision.
const (
	DecisionAllow           Decision = "allow"
	DecisionDeny            Decision = "deny"
	DecisionRequireApproval Decision = "require_approval"
)

// Valid indicates whether the value is a known member of the Decision enum.
func (e Decision) Valid() bool {
	switch e {
	case DecisionAllow:
		return true
	case DecisionDeny:
		return true
	case DecisionRequireApproval:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAssistant Role = "assistant"
	RoleUser      Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAssistant:
		return true
	case RoleUser:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusCancelled RunStatus = "cancelled"
	RunStatusFailed    RunStatus = "failed"
	RunStatusQueued    RunStatus = "queued"
	RunStatusRunning   RunStatus = "running"
	RunStatusSucceeded RunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusCancelled:
		return true
	case RunStatusFailed:
		return true
	case RunStatusQueued:
		return true
	case RunStatusRunning:
		return true
	case RunStatusSucceeded:
		return true
	default:
		return false
	}
}

// Answer defines model for Answer.
type Answer struct {
	Approved bool   `json:"approved"`
	Reason   string `json:"reason,omitempty"`
}

// ApprovalRequest A call that policy marked as requiring approval. Secrets are already
// redacted from it.
type ApprovalRequest struct {
	// Args Any JSON value, kept as written.
	Args      JSON      `json:"args"`
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt When the request is rejected if no one answers it.
	ExpiresAt time.Time `json:"expires_at"`
	Harness   string    `json:"harness"`

	// ID Identifies the request when answering it.
	ID      string   `json:"id"`
	Reasons []string `json:"reasons"`
	RunID   string   `json:"run_id"`
	Tool    string   `json:"tool"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent string

// AuditRecord One decision, approval or result the tool gateway recorded.
type AuditRecord struct {
	// Approver Who approved or rejected the call, if anyone did.
	Approver string `json:"approver,omitempty"`

	// Args Any JSON value, kept as written.
	Args       JSON       `json:"args,omitempty"`
	CallID     string     `json:"call_id"`
	Decision   Decision   `json:"decision"`
	Error      string     `json:"error,omitempty"`
	Event      AuditEvent `json:"event"`
	Reason     string     `json:"reason,omitempty"`
	RecordedAt time.Time  `json:"recorded_at"`

	// Result Any JSON value, kept as written.
	Result JSON   `json:"result,omitempty"`
	RunID  string `json:"run_id"`
	Tool   string `json:"tool"`
}

// CreateRun defines model for CreateRun.
type CreateRun struct {
	// Harness The harness to run, by name; the run uses its latest version.
	Harness string `json:"harness"`
	Input   string `json:"input"`
}

// Decision defines model for Decision.
type Decision string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// FollowUp defines model for FollowUp.
type FollowUp struct {
	Input string `json:"input"`
}

// Harness A declarative definition of an agent.
type Harness struct {
	Instructions string       `json:"instructions"`
	Limits       Limits       `json:"limits"`
	Model        HarnessModel `json:"model"`
	Name         string       `json:"name"`

	// Policy Rego modules in package agenty.tool that tighten central policy
	// for this harness.
	Policy []PolicyModule `json:"policy,omitempty"`

	// Tools The granted tools.
	Tools []string `json:"tools,omitempty"`
}

// HarnessModel defines model for HarnessModel.
type HarnessModel struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
}

// HarnessVersion defines model for HarnessVersion.
type HarnessVersion struct {
	CreatedAt time.Time `json:"created_at"`

	// Harness A declarative definition of an agent.
	Harness Harness `json:"harness"`

	// ID Identifies the version across all harnesses.
	ID      int64 `json:"id"`
	Version int   `json:"version"`
}

// JSON Any JSON value, kept as written.
type JSON = json.RawMessage

// Limits defines model for Limits.
type Limits struct {
	// MaxSteps Bounds the model calls of a run.
	MaxSteps int `json:"max_steps"`

	// MaxToolCalls Bounds the tool calls of a run, denied ones included.
	MaxToolCalls int `json:"max_tool_calls"`
}

// Me defines model for Me.
type Me struct {
	User string `json:"user"`

	// Workspaces The workspaces the user is a member of, sorted.
	Workspaces []string `json:"workspaces"`
}

// PolicyModule defines model for PolicyModule.
type PolicyModule struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

// ProviderPart A message in the form of the provider that generated it, kept so it
// can be sent to the model again.
type ProviderPart struct {
	// Data Any JSON value, kept as written.
	Data JSON   `json:"data"`
	Name string `json:"name"`
}

// Role defines model for Role.
type Role string

// Run defines model for Run.
type Run struct {
	// ConversationID The conversation the run belongs to, named by the ID of its
	// first run, which may be this one.
	ConversationID string    `json:"conversation_id"`
	CreatedAt      time.Time `json:"created_at"`

	// Error Why the run failed, or who cancelled it.
	Error string `json:"error,omitempty"`

	// FinishedAt Unset until the run has finished.
	FinishedAt time.Time `json:"finished_at,omitempty,omitzero"`

	// Follows The run whose conversation this run continues, if any.
	Follows          string `json:"follows,omitempty"`
	Harness          string `json:"harness"`
	HarnessVersion   int    `json:"harness_version"`
	HarnessVersionID int64  `json:"harness_version_id"`
	ID               string `json:"id"`
	Input            string `json:"input"`
	Output           string `json:"output"`

	// StartedBy The user who started the run.
	StartedBy string    `json:"started_by"`
	Status    RunStatus `json:"status"`
	Steps     int       `json:"steps"`

	// Usage The tokens of the model calls that wrote the run's replies so
	// far. A call that failed, such as one whose reply was cut off, is
	// not counted.
	Usage Usage `json:"usage"`
}

// RunList defines model for RunList.
type RunList struct {
	// Next The before parameter of the next page, which may be empty.
	Next string `json:"next,omitempty"`
	Runs []Run  `json:"runs"`
}

// RunStatus defines model for RunStatus.
type RunStatus string

// ToolCall defines model for ToolCall.
type ToolCall struct {
	// Args Any JSON value, kept as written.
	Args JSON   `json:"args,omitempty"`
	ID   string `json:"id"`
	Name string `json:"name"`
}

// ToolResult defines model for ToolResult.
type ToolResult struct {
	CallID  string `json:"call_id"`
	Content string `json:"content"`
	IsError bool   `json:"is_error,omitempty"`
}

// TranscriptMessage One message of a run's conversation with the model: the input, a
// model reply, or the results of the reply's tool calls.
type TranscriptMessage struct {
	CreatedAt time.Time `json:"created_at"`

	// Position The message's index in the conversation.
	Position    int          `json:"position"`
	Provider    ProviderPart `json:"provider,omitempty,omitzero"`
	Role        Role         `json:"role"`
	Text        string       `json:"text,omitempty"`
	ToolCalls   []ToolCall   `json:"tool_calls,omitempty"`
	ToolResults []ToolResult `json:"tool_results,omitempty"`

	// Usage The tokens of the model call that wrote a reply.
	Usage Usage `json:"usage,omitempty,omitzero"`
}

// Usage The tokens of model calls. Input the provider read from its prompt
// cache, or wrote to it, is counted apart from the rest of the input.
type Usage struct {
	// CacheReadTokens Input tokens read from the prompt cache.
	CacheReadTokens int64 `json:"cache_read_tokens"`

	// CacheWriteTokens Input tokens written to the prompt cache.
	CacheWriteTokens int64 `json:"cache_write_tokens"`

	// InputTokens Input tokens neither read from nor written to the cache.
	InputTokens  int64 `json:"input_tokens"`
	OutputTokens int64 `json:"output_tokens"`
}

// RunID defines model for RunID.
type RunID = string

// Workspace defines model for Workspace.
type Workspace = string

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	// Harness Only the runs of this harness.
	Harness string `form:"harness,omitempty" json:"harness,omitempty"`

	// Status Only the runs with this status.
	Status RunStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit The page size.
	Limit int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Continue after the run with this ID, as RunList.next gives it. A
	// run that is not one of the workspace's gives an empty page.
	Before string `form:"before,omitempty" json:"before,omitempty"`
}

// PutHarnessJSONRequestBody defines body for PutHarness for application/json ContentType.
type PutHarnessJSONRequestBody = Harness

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRun

// AnswerApprovalJSONRequestBody defines body for AnswerApproval for application/json ContentType.
type AnswerApprovalJSONRequestBody = Answer

// FollowUpRunJSONRequestBody defines body for FollowUpRun for application/json ContentType.
type FollowUpRunJSONRequestBody = FollowUp
