// Package store keeps Agenty's state in PostgreSQL: harness versions, runs,
// their transcripts, and the audit log. Harnesses belong to a workspace, and
// so do the runs of them. Queries are generated by sqlc from queries/ into db/;
// the schema lives in migrations/ and is applied by Open.
package store

//go:generate go run github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1 generate -f ../../sqlc.yaml

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"math"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"github.com/jangraefen/agenty/internal/harness"
	"github.com/jangraefen/agenty/internal/model"
	"github.com/jangraefen/agenty/internal/must"
	"github.com/jangraefen/agenty/internal/store/db"
	"github.com/jangraefen/agenty/internal/toolgateway"
)

//go:embed migrations/*.sql
var migrations embed.FS

// ErrNotFound is returned when a harness or run does not exist.
var ErrNotFound = errors.New("not found")

// Store is Agenty's state in PostgreSQL.
type Store struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

// Open connects to the database at url and applies every migration it has
// not applied yet. Close the Store to close its connections.
func Open(ctx context.Context, url string) (*Store, error) {
	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}
	if err := migrate(ctx, pool); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: migrate: %w", err)
	}
	return &Store{pool: pool, queries: db.New(pool)}, nil
}

func migrate(ctx context.Context, pool *pgxpool.Pool) error {
	sqlDB := stdlib.OpenDBFromPool(pool)
	provider, err := goose.NewProvider(goose.DialectPostgres, sqlDB, must.Value(fs.Sub(migrations, "migrations")))
	if err != nil {
		return errors.Join(err, sqlDB.Close())
	}
	_, err = provider.Up(ctx)
	return errors.Join(err, sqlDB.Close())
}

// Close closes the database connections.
func (s *Store) Close() {
	s.pool.Close()
}

// HarnessVersion is one stored version of a harness.
type HarnessVersion struct {
	// ID identifies the version across all harnesses; runs refer to it.
	ID int64
	// Workspace is the workspace the harness belongs to.
	Workspace string
	Version   int
	Harness   harness.Harness
	CreatedAt time.Time
}

// PutHarness stores h as the next version of its harness in workspace, after
// validating it. If h equals the latest version, nothing is stored and that version is
// returned, so applying an unchanged harness is a no-op. Concurrent puts of
// one harness are serialized, so each gets its own version.
func (s *Store) PutHarness(ctx context.Context, workspace string, h harness.Harness) (HarnessVersion, error) {
	if err := h.Validate(); err != nil {
		return HarnessVersion{}, fmt.Errorf("store: invalid harness: %w", err)
	}
	definition := canonical(h)

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return HarnessVersion{}, fmt.Errorf("store: %w", err)
	}
	q := s.queries.WithTx(tx)
	// A workspace name never holds a slash.
	if err := q.LockHarnessName(ctx, workspace+"/"+h.Name); err != nil {
		return HarnessVersion{}, errors.Join(fmt.Errorf("store: %w", err), tx.Rollback(ctx))
	}
	next := int32(1)
	latest, err := q.LatestHarnessVersion(ctx, db.LatestHarnessVersionParams{Workspace: workspace, Name: h.Name})
	switch {
	case errors.Is(err, pgx.ErrNoRows):
	case err != nil:
		return HarnessVersion{}, errors.Join(fmt.Errorf("store: %w", err), tx.Rollback(ctx))
	default:
		v, err := harnessVersion(latest)
		if err != nil {
			return HarnessVersion{}, errors.Join(err, tx.Rollback(ctx))
		}
		if bytes.Equal(canonical(v.Harness), definition) {
			return v, tx.Rollback(ctx)
		}
		next = latest.Version + 1
	}
	row, err := q.InsertHarnessVersion(ctx, db.InsertHarnessVersionParams{Workspace: workspace, Name: h.Name, Version: next, Definition: definition})
	if err != nil {
		return HarnessVersion{}, errors.Join(fmt.Errorf("store: %w", err), tx.Rollback(ctx))
	}
	if err := tx.Commit(ctx); err != nil {
		return HarnessVersion{}, fmt.Errorf("store: %w", err)
	}
	return harnessVersion(row)
}

// canonical is the stored form of h: its JSON, with empty lists written as
// null, so that a harness without tools or policy has one form.
func canonical(h harness.Harness) []byte {
	if len(h.Tools) == 0 {
		h.Tools = nil
	}
	if len(h.Policy) == 0 {
		h.Policy = nil
	}
	return must.Value(json.Marshal(h))
}

// Harness returns the latest version of the named harness in workspace.
func (s *Store) Harness(ctx context.Context, workspace, name string) (HarnessVersion, error) {
	row, err := s.queries.LatestHarnessVersion(ctx, db.LatestHarnessVersionParams{Workspace: workspace, Name: name})
	if err != nil {
		return HarnessVersion{}, notFound("harness "+name, err)
	}
	return harnessVersion(row)
}

// HarnessVersionByID returns the harness version with the given ID.
func (s *Store) HarnessVersionByID(ctx context.Context, id int64) (HarnessVersion, error) {
	row, err := s.queries.HarnessVersionByID(ctx, id)
	if err != nil {
		return HarnessVersion{}, notFound(fmt.Sprintf("harness version %d", id), err)
	}
	return harnessVersion(row)
}

// Harnesses returns the latest version of every harness in workspace, sorted
// by name.
func (s *Store) Harnesses(ctx context.Context, workspace string) ([]HarnessVersion, error) {
	rows, err := s.queries.LatestHarnessVersions(ctx, workspace)
	if err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}
	out := make([]HarnessVersion, 0, len(rows))
	for _, row := range rows {
		v, err := harnessVersion(row)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, nil
}

func harnessVersion(row db.HarnessVersion) (HarnessVersion, error) {
	var h harness.Harness
	if err := json.Unmarshal(row.Definition, &h); err != nil {
		return HarnessVersion{}, fmt.Errorf("store: harness %s version %d: %w", row.Name, row.Version, err)
	}
	return HarnessVersion{ID: row.ID, Workspace: row.Workspace, Version: int(row.Version), Harness: h, CreatedAt: row.CreatedAt}, nil
}

// RunStatus is the state of a run.
type RunStatus string

const (
	RunRunning   RunStatus = "running"
	RunSucceeded RunStatus = "succeeded"
	RunFailed    RunStatus = "failed"
	// RunCancelled is a run a user cancelled.
	RunCancelled RunStatus = "cancelled"
)

// Run is a stored run.
type Run struct {
	ID               string
	HarnessVersionID int64
	// Harness and HarnessVersion name the harness version the run runs.
	Harness        string
	HarnessVersion int
	// StartedBy names the user who started the run.
	StartedBy string
	Input     string
	Status    RunStatus
	Output    string
	Steps     int
	Error     string
	CreatedAt time.Time
	// FinishedAt is nil while the run is running.
	FinishedAt *time.Time
}

// NewRun is a run to store.
type NewRun struct {
	ID               string
	HarnessVersionID int64
	Input            string
	// StartedBy names the user who starts the run.
	StartedBy string
}

// CreateRun stores a new running run. It belongs to the workspace of its
// harness version.
func (s *Store) CreateRun(ctx context.Context, r NewRun) error {
	if err := s.queries.InsertRun(ctx, db.InsertRunParams{ID: r.ID, HarnessVersionID: r.HarnessVersionID, Input: r.Input, StartedBy: r.StartedBy}); err != nil {
		return fmt.Errorf("store: run %s: %w", r.ID, err)
	}
	return nil
}

// FinishRun records the end of a running run. Finishing a run that does not
// exist or has already finished returns ErrNotFound.
func (s *Store) FinishRun(ctx context.Context, id string, status RunStatus, output string, steps int, runErr string) error {
	if status == RunRunning {
		return fmt.Errorf("store: run %s: cannot finish as %s", id, status)
	}
	n, err := s.queries.FinishRun(ctx, db.FinishRunParams{ID: id, Status: string(status), Output: output, Steps: int32(steps), Error: runErr}) //nolint:gosec // G115: steps is bounded by the harness's max_steps.
	switch {
	case err != nil:
		return fmt.Errorf("store: run %s: %w", id, err)
	case n == 0:
		return fmt.Errorf("store: running run %s: %w", id, ErrNotFound)
	}
	return nil
}

// Run returns the run with the given ID in workspace. A run of another
// workspace is not found.
func (s *Store) Run(ctx context.Context, workspace, id string) (Run, error) {
	row, err := s.queries.GetRun(ctx, db.GetRunParams{ID: id, Workspace: workspace})
	if err != nil {
		return Run{}, notFound("run "+id, err)
	}
	return run(row.Run, row.Harness, row.HarnessVersion), nil
}

// RunFilter selects runs to list.
type RunFilter struct {
	// Harness and Status, when set, select the runs of that harness or with
	// that status.
	Harness string
	Status  RunStatus
	// Before, when set, lists the runs after the run with that ID, in the
	// order Runs returns them: a page after one ending with that run.
	Before string
	// Limit is the most runs to return; it must be greater than 0.
	Limit int
}

// Runs lists the runs of workspace that f selects, newest first.
func (s *Store) Runs(ctx context.Context, workspace string, f RunFilter) ([]Run, error) {
	if f.Limit <= 0 || f.Limit > math.MaxInt32 {
		return nil, fmt.Errorf("store: runs: limit %d is out of range", f.Limit)
	}
	rows, err := s.queries.ListRuns(ctx, db.ListRunsParams{
		Workspace: workspace,
		Harness:   optional(f.Harness),
		Status:    optional(string(f.Status)),
		Before:    optional(f.Before),
		MaxRows:   int32(f.Limit),
	})
	if err != nil {
		return nil, fmt.Errorf("store: runs: %w", err)
	}
	out := make([]Run, len(rows))
	for i, row := range rows {
		out[i] = run(row.Run, row.Harness, row.HarnessVersion)
	}
	return out, nil
}

// optional is s as a nullable query argument: empty is NULL.
func optional(s string) pgtype.Text {
	return pgtype.Text{String: s, Valid: s != ""}
}

func run(row db.Run, harness string, version int32) Run {
	return Run{
		ID:               row.ID,
		HarnessVersionID: row.HarnessVersionID,
		Harness:          harness,
		HarnessVersion:   int(version),
		StartedBy:        row.StartedBy,
		Input:            row.Input,
		Status:           RunStatus(row.Status),
		Output:           row.Output,
		Steps:            int(row.Steps),
		Error:            row.Error,
		CreatedAt:        row.CreatedAt,
		FinishedAt:       row.FinishedAt,
	}
}

// FailRunningRuns marks every run that is still running as failed with
// reason, and returns how many it marked. A server calls it on startup: a
// run cannot outlive the process that ran it.
func (s *Store) FailRunningRuns(ctx context.Context, reason string) (int64, error) {
	n, err := s.queries.FailRunningRuns(ctx, reason)
	if err != nil {
		return 0, fmt.Errorf("store: %w", err)
	}
	return n, nil
}

var _ toolgateway.Audit = (*Store)(nil)

// Record appends rec to the audit log. The record's run must exist. An error
// means the record may not be stored, and the gateway then does not execute
// the call. Content never makes recording fail: PostgreSQL rejects NUL bytes
// and invalid UTF-8 in text, so those are replaced, and anything that is not
// valid JSON, such as malformed arguments from a model, is stored as a JSON
// string.
func (s *Store) Record(ctx context.Context, rec toolgateway.Record) error {
	err := s.queries.InsertAuditRecord(ctx, db.InsertAuditRecordParams{
		RunID:    text(rec.RunID),
		CallID:   text(rec.CallID),
		Event:    text(string(rec.Event)),
		Tool:     text(rec.Tool),
		Args:     jsonText(rec.Args),
		Decision: text(string(rec.Decision)),
		Reason:   text(rec.Reason),
		Approver: text(rec.Approver),
		Result:   jsonText(rec.Result),
		Error:    text(rec.Err),
	})
	if err != nil {
		return fmt.Errorf("store: audit: %w", err)
	}
	return nil
}

// AuditRecord is a stored audit record.
type AuditRecord struct {
	toolgateway.Record
	RecordedAt time.Time
}

// AuditRecords returns the audit records of a run, in the order they were
// recorded.
func (s *Store) AuditRecords(ctx context.Context, runID string) ([]AuditRecord, error) {
	rows, err := s.queries.AuditRecordsOfRun(ctx, runID)
	if err != nil {
		return nil, fmt.Errorf("store: audit: %w", err)
	}
	out := make([]AuditRecord, len(rows))
	for i, row := range rows {
		out[i] = AuditRecord{
			Record: toolgateway.Record{
				RunID:    row.RunID,
				CallID:   row.CallID,
				Event:    toolgateway.Event(row.Event),
				Tool:     row.Tool,
				Args:     row.Args,
				Decision: toolgateway.Decision(row.Decision),
				Reason:   row.Reason,
				Approver: row.Approver,
				Result:   row.Result,
				Err:      row.Error,
			},
			RecordedAt: row.RecordedAt,
		}
	}
	return out, nil
}

// text makes s storable in a text column, which accepts neither NUL bytes
// nor invalid UTF-8: both become U+FFFD.
func text(s string) string {
	return strings.ReplaceAll(strings.ToValidUTF8(s, "\uFFFD"), "\x00", "\uFFFD")
}

// jsonText makes raw storable in a json column: empty stays NULL, invalid
// UTF-8 becomes U+FFFD, and anything that is then still not valid JSON, such
// as text with a raw NUL byte, becomes a JSON string, where json.Marshal
// escapes the NUL.
func jsonText(raw json.RawMessage) []byte {
	if len(raw) == 0 {
		return nil
	}
	valid := []byte(strings.ToValidUTF8(string(raw), "\uFFFD"))
	if json.Valid(valid) {
		return valid
	}
	return must.Value(json.Marshal(string(valid)))
}

func notFound(what string, err error) error {
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("store: %s: %w", what, ErrNotFound)
	}
	return fmt.Errorf("store: %s: %w", what, err)
}

// TranscriptMessage is a stored message of a run's transcript.
type TranscriptMessage struct {
	// Position is the message's index in the run's conversation.
	Position int
	model.Message
	CreatedAt time.Time
}

// AppendMessage stores msg at position in the transcript of the run runID,
// which must exist. A position is written once. As with Record, content never
// makes storing fail: invalid UTF-8 and NUL bytes in the text are replaced,
// and tool call arguments and provider parts that are not valid JSON are kept
// as a JSON string. A provider part's JSON is kept as written, so the provider
// can replay it exactly.
func (s *Store) AppendMessage(ctx context.Context, runID string, position int, msg model.Message) error {
	calls := make([]model.ToolCall, len(msg.ToolCalls))
	for i, c := range msg.ToolCalls {
		c.Args = jsonText(c.Args)
		calls[i] = c
	}
	var provider string
	var providerData []byte
	if p := msg.Provider; p != nil {
		if p.Name == "" {
			return fmt.Errorf("store: run %s: message %d: provider part without a name", runID, position)
		}
		provider, providerData = text(p.Name), jsonText(p.Data)
	}
	err := s.queries.InsertRunMessage(ctx, db.InsertRunMessageParams{
		RunID:        text(runID),
		Position:     int32(position), //nolint:gosec // G115: a position is bounded by the harness's max_steps.
		Role:         text(string(msg.Role)),
		Text:         text(msg.Text),
		ToolCalls:    jsonList(calls),
		ToolResults:  jsonList(msg.ToolResults),
		Provider:     provider,
		ProviderData: providerData,
	})
	if err != nil {
		return fmt.Errorf("store: run %s: message %d: %w", runID, position, err)
	}
	return nil
}

// jsonList encodes a list for a json column; an empty list stays NULL.
// json.Marshal replaces invalid UTF-8 and escapes NUL, which json accepts.
func jsonList[T any](list []T) []byte {
	if len(list) == 0 {
		return nil
	}
	return must.Value(json.Marshal(list))
}

// Transcript returns the stored transcript of a run, in order. A run without
// messages, or one that does not exist, has an empty transcript.
func (s *Store) Transcript(ctx context.Context, runID string) ([]TranscriptMessage, error) {
	rows, err := s.queries.RunMessages(ctx, runID)
	if err != nil {
		return nil, fmt.Errorf("store: run %s: transcript: %w", runID, err)
	}
	out := make([]TranscriptMessage, len(rows))
	for i, row := range rows {
		msg := model.Message{Role: model.Role(row.Role), Text: row.Text}
		if row.ToolCalls != nil {
			if err := json.Unmarshal(row.ToolCalls, &msg.ToolCalls); err != nil {
				return nil, fmt.Errorf("store: run %s: message %d: tool calls: %w", runID, row.Position, err)
			}
		}
		if row.ToolResults != nil {
			if err := json.Unmarshal(row.ToolResults, &msg.ToolResults); err != nil {
				return nil, fmt.Errorf("store: run %s: message %d: tool results: %w", runID, row.Position, err)
			}
		}
		if row.Provider != "" {
			msg.Provider = &model.ProviderPart{Name: row.Provider, Data: row.ProviderData}
		}
		out[i] = TranscriptMessage{Position: int(row.Position), Message: msg, CreatedAt: row.CreatedAt}
	}
	return out, nil
}
