// Package store keeps Agenty's state in PostgreSQL: harness versions, runs,
// their transcripts, and the audit log. Harnesses belong to a workspace, and
// so do the runs of them. Queries are generated by sqlc from queries/ into db/;
// the schema lives in migrations/ and is applied by Open.
package store

//go:generate go run github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1 generate -f ../../sqlc.yaml

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"math"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"github.com/jangraefen/agenty/internal/auditlog"
	"github.com/jangraefen/agenty/internal/harness"
	"github.com/jangraefen/agenty/internal/model"
	"github.com/jangraefen/agenty/internal/must"
	"github.com/jangraefen/agenty/internal/store/db"
)

//go:embed migrations/*.sql
var migrations embed.FS

// ErrNotFound is returned when a harness or run does not exist.
var ErrNotFound = errors.New("not found")

// ErrConflict is returned when a run is to follow a run that another run
// already follows.
var ErrConflict = errors.New("conflict")

// Store is Agenty's state in PostgreSQL.
type Store struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

// Open connects to the database at url and applies every migration it has
// not applied yet. Close the Store to close its connections.
func Open(ctx context.Context, url string) (*Store, error) {
	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}
	if err := migrate(ctx, pool); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: migrate: %w", err)
	}
	return &Store{pool: pool, queries: db.New(pool)}, nil
}

func migrate(ctx context.Context, pool *pgxpool.Pool) error {
	sqlDB := stdlib.OpenDBFromPool(pool)
	provider, err := goose.NewProvider(goose.DialectPostgres, sqlDB, must.Value(fs.Sub(migrations, "migrations")))
	if err != nil {
		return errors.Join(err, sqlDB.Close())
	}
	_, err = provider.Up(ctx)
	return errors.Join(err, sqlDB.Close())
}

// inTx runs f in a transaction, which it commits unless f fails. The
// transaction reads committed data, whatever the database's default, so an
// append to the audit log in it sees the event appended just before it.
func (s *Store) inTx(ctx context.Context, f func(*db.Queries) error) error {
	tx, err := s.pool.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.ReadCommitted})
	if err != nil {
		return fmt.Errorf("store: %w", err)
	}
	if err := f(s.queries.WithTx(tx)); err != nil {
		return errors.Join(err, tx.Rollback(ctx))
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("store: %w", err)
	}
	return nil
}

// Close closes the database connections.
func (s *Store) Close() {
	s.pool.Close()
}

// HarnessVersion is one stored version of a harness.
type HarnessVersion struct {
	// ID identifies the version across all harnesses; runs refer to it.
	ID int64
	// Workspace is the workspace the harness belongs to.
	Workspace string
	Version   int
	Harness   harness.Harness
	CreatedAt time.Time
}

// PutHarness stores h as the next version of its harness in workspace, after
// validating it. If h equals the latest version, nothing is stored and that version is
// returned, so applying an unchanged harness is a no-op. Concurrent puts of
// one harness are serialized, so each gets its own version.
func (s *Store) PutHarness(ctx context.Context, workspace, user string, h harness.Harness) (HarnessVersion, error) {
	if err := h.Validate(); err != nil {
		return HarnessVersion{}, fmt.Errorf("store: invalid harness: %w", err)
	}
	definition := canonical(h)

	var stored HarnessVersion
	_, err := s.withEvents(ctx, func(q *db.Queries) ([]auditlog.Event, error) {
		// A workspace name never holds a slash.
		if err := q.LockHarnessName(ctx, workspace+"/"+h.Name); err != nil {
			return nil, fmt.Errorf("store: %w", err)
		}
		next := int32(1)
		latest, err := q.LatestHarnessVersion(ctx, db.LatestHarnessVersionParams{Workspace: workspace, Name: h.Name})
		switch {
		case errors.Is(err, pgx.ErrNoRows):
		case err != nil:
			return nil, fmt.Errorf("store: %w", err)
		default:
			if stored, err = harnessVersion(latest); err != nil {
				return nil, err
			}
			if bytes.Equal(canonical(stored.Harness), definition) {
				return nil, nil
			}
			next = latest.Version + 1
		}
		row, err := q.InsertHarnessVersion(ctx, db.InsertHarnessVersionParams{Workspace: workspace, Name: h.Name, Version: next, Definition: definition})
		if err != nil {
			return nil, fmt.Errorf("store: %w", err)
		}
		if stored, err = harnessVersion(row); err != nil {
			return nil, err
		}
		return []auditlog.Event{harnessChanged(workspace, user, h.Name, next)}, nil
	})
	if err != nil {
		return HarnessVersion{}, err
	}
	return stored, nil
}

// canonical is the stored form of h: its JSON, with empty lists written as
// null, so that a harness without tools or policy has one form.
func canonical(h harness.Harness) []byte {
	if len(h.Tools) == 0 {
		h.Tools = nil
	}
	if len(h.Policy) == 0 {
		h.Policy = nil
	}
	return must.Value(json.Marshal(h))
}

// Harness returns the latest version of the named harness in workspace.
func (s *Store) Harness(ctx context.Context, workspace, name string) (HarnessVersion, error) {
	row, err := s.queries.LatestHarnessVersion(ctx, db.LatestHarnessVersionParams{Workspace: workspace, Name: name})
	if err != nil {
		return HarnessVersion{}, notFound("harness "+name, err)
	}
	return harnessVersion(row)
}

// HarnessVersionByID returns the harness version with the given ID.
func (s *Store) HarnessVersionByID(ctx context.Context, id int64) (HarnessVersion, error) {
	row, err := s.queries.HarnessVersionByID(ctx, id)
	if err != nil {
		return HarnessVersion{}, notFound(fmt.Sprintf("harness version %d", id), err)
	}
	return harnessVersion(row)
}

// Harnesses returns the latest version of every harness in workspace, sorted
// by name.
func (s *Store) Harnesses(ctx context.Context, workspace string) ([]HarnessVersion, error) {
	rows, err := s.queries.LatestHarnessVersions(ctx, workspace)
	if err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}
	out := make([]HarnessVersion, 0, len(rows))
	for _, row := range rows {
		v, err := harnessVersion(row)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, nil
}

func harnessVersion(row db.HarnessVersion) (HarnessVersion, error) {
	var h harness.Harness
	if err := json.Unmarshal(row.Definition, &h); err != nil {
		return HarnessVersion{}, fmt.Errorf("store: harness %s version %d: %w", row.Name, row.Version, err)
	}
	return HarnessVersion{ID: row.ID, Workspace: row.Workspace, Version: int(row.Version), Harness: h, CreatedAt: row.CreatedAt}, nil
}

// RunStatus is the state of a run.
type RunStatus string

const (
	// RunQueued is a run waiting for a worker.
	RunQueued  RunStatus = "queued"
	RunRunning RunStatus = "running"
	// RunWaiting is a run whose call waits for approval; no worker holds it.
	RunWaiting   RunStatus = "waiting"
	RunSucceeded RunStatus = "succeeded"
	RunFailed    RunStatus = "failed"
	// RunCancelled is a run a user cancelled.
	RunCancelled RunStatus = "cancelled"
)

// Finished reports whether the run has ended: it is neither queued, nor
// running, nor waiting.
func (r Run) Finished() bool {
	return r.Status != RunQueued && r.Status != RunRunning && r.Status != RunWaiting
}

// Run is a stored run.
type Run struct {
	ID               string
	HarnessVersionID int64
	// Harness and HarnessVersion name the harness version the run runs.
	Harness        string
	HarnessVersion int
	// StartedBy names the user who started the run.
	StartedBy string
	Input     string
	Status    RunStatus
	Output    string
	Steps     int
	Error     string
	CreatedAt time.Time
	// FinishedAt is nil until the run has finished.
	FinishedAt *time.Time
	// ConversationID names the conversation the run belongs to by the ID of
	// its first run, which may be this one.
	ConversationID string
	// Follows is the ID of the run this run continues the conversation of,
	// if any.
	Follows string
	// PromptDigest identifies what the run sent the model before the
	// conversation: its model, instructions and tools. HistoryDigest
	// identifies the conversation of earlier runs it sent before its input.
	// A run that never ran has neither.
	PromptDigest, HistoryDigest string
	// Usage sums the usage of the run's stored replies.
	Usage model.Usage
}

// NewRun is a run to store.
type NewRun struct {
	ID               string
	HarnessVersionID int64
	Input            string
	// StartedBy names the user who starts the run.
	StartedBy string
	// Follows, when set, is the ID of the run whose conversation the run
	// continues.
	Follows string
}

// uniqueViolation is PostgreSQL's error code for a violated unique constraint.
const uniqueViolation = "23505"

// CreateRun stores a new queued run and returns it as stored, before a
// worker may claim it. It belongs to the workspace of its harness version. A
// run that follows another joins its conversation. It follows only a run its
// own starter started, so a conversation is one user's: following any other
// run, or none that is stored, returns ErrNotFound. Following a run that
// another run already follows returns ErrConflict, so a conversation never
// branches.
func (s *Store) CreateRun(ctx context.Context, r NewRun) (Run, error) {
	var created Run
	_, err := s.withEvents(ctx, func(q *db.Queries) ([]auditlog.Event, error) {
		row, err := q.InsertRun(ctx, db.InsertRunParams{ID: r.ID, HarnessVersionID: r.HarnessVersionID, Input: r.Input, StartedBy: r.StartedBy, Follows: optional(r.Follows)})
		var pgErr *pgconn.PgError
		switch {
		case errors.As(err, &pgErr) && pgErr.Code == uniqueViolation && pgErr.ConstraintName == "runs_follows_key":
			return nil, fmt.Errorf("store: run %s: run %s is already followed: %w", r.ID, r.Follows, ErrConflict)
		case errors.Is(err, pgx.ErrNoRows):
			return nil, fmt.Errorf("store: run %s: run %s of %s: %w", r.ID, r.Follows, r.StartedBy, ErrNotFound)
		case err != nil:
			return nil, fmt.Errorf("store: run %s: %w", r.ID, err)
		}
		created = run(row.Run, row.Harness, row.HarnessVersion)
		return []auditlog.Event{runStarted(created, row.Workspace)}, nil
	})
	if err != nil {
		return Run{}, err
	}
	return created, nil
}

// ClaimedRun is a run a worker claimed, and its workspace.
type ClaimedRun struct {
	ID, Workspace string
}

// ClaimRun marks the oldest queued run as running and returns it. It reports
// false if no run is queued. Each run is claimed once, also by concurrent
// claims.
func (s *Store) ClaimRun(ctx context.Context) (ClaimedRun, bool, error) {
	row, err := s.queries.ClaimRun(ctx)
	switch {
	case errors.Is(err, pgx.ErrNoRows):
		return ClaimedRun{}, false, nil
	case err != nil:
		return ClaimedRun{}, false, fmt.Errorf("store: claim a run: %w", err)
	}
	return ClaimedRun{ID: row.ID, Workspace: row.Workspace}, true, nil
}

// IdleRun is a run no worker holds that has not finished, queued or waiting,
// with its workspace and harness.
type IdleRun struct {
	ID        string
	Status    RunStatus
	Workspace string
	Harness   string
	// Owner started the run, and so its conversation.
	Owner string
}

// IdleRuns returns the queued and waiting runs, oldest first.
func (s *Store) IdleRuns(ctx context.Context) ([]IdleRun, error) {
	rows, err := s.queries.IdleRuns(ctx)
	if err != nil {
		return nil, fmt.Errorf("store: idle runs: %w", err)
	}
	out := make([]IdleRun, len(rows))
	for i, r := range rows {
		out[i] = IdleRun{ID: r.ID, Status: RunStatus(r.Status), Workspace: r.Workspace, Harness: r.Harness, Owner: r.Owner}
	}
	return out, nil
}

// CancelIdleRun records a queued or waiting run as cancelled, giving why, and
// withdraws the approval request it waits for. It reports false if the run
// is neither, such as one a worker has claimed.
func (s *Store) CancelIdleRun(ctx context.Context, id, why string) (bool, error) {
	cancelled := false
	_, err := s.withEvents(ctx, func(q *db.Queries) ([]auditlog.Event, error) {
		// The request first, then the run, as AnswerApproval and
		// ExpireApprovals lock them.
		if err := q.WithdrawApprovals(ctx, db.WithdrawApprovalsParams{RunID: id, Reason: why}); err != nil {
			return nil, fmt.Errorf("store: run %s: %w", id, err)
		}
		rows, err := q.CancelIdleRun(ctx, db.CancelIdleRunParams{ID: id, Error: why})
		if err != nil || len(rows) == 0 {
			return nil, wrapRun(id, err)
		}
		cancelled = true
		return []auditlog.Event{runFinished(rows[0].Workspace, id, RunCancelled, rows[0].Steps, why)}, nil
	})
	return cancelled, err
}

// SetRunDigests records what a running run sends the model; see Run.
func (s *Store) SetRunDigests(ctx context.Context, id, prompt, history string) error {
	n, err := s.queries.SetRunDigests(ctx, db.SetRunDigestsParams{ID: id, PromptDigest: prompt, HistoryDigest: history})
	switch {
	case err != nil:
		return fmt.Errorf("store: run %s: %w", id, err)
	case n == 0:
		return fmt.Errorf("store: running run %s: %w", id, ErrNotFound)
	}
	return nil
}

// FinishRun records the end of a running run. Finishing a run that does not
// exist or has already finished returns ErrNotFound.
func (s *Store) FinishRun(ctx context.Context, id string, status RunStatus, output string, steps int, runErr string) error {
	if status == RunRunning || status == RunQueued {
		return fmt.Errorf("store: run %s: cannot finish as %s", id, status)
	}
	_, err := s.withEvents(ctx, func(q *db.Queries) ([]auditlog.Event, error) {
		workspace, err := q.FinishRun(ctx, db.FinishRunParams{ID: id, Status: string(status), Output: output, Steps: int32(steps), Error: runErr}) //nolint:gosec // G115: steps is bounded by the harness's max_steps.
		switch {
		case errors.Is(err, pgx.ErrNoRows):
			return nil, fmt.Errorf("store: running run %s: %w", id, ErrNotFound)
		case err != nil:
			return nil, fmt.Errorf("store: run %s: %w", id, err)
		}
		return []auditlog.Event{runFinished(workspace, id, status, int32(steps), runErr)}, nil //nolint:gosec // G115: as above.
	})
	return err
}

// Run returns the run with the given ID in workspace. A run of another
// workspace is not found.
func (s *Store) Run(ctx context.Context, workspace, id string) (Run, error) {
	row, err := s.queries.GetRun(ctx, db.GetRunParams{ID: id, Workspace: workspace})
	if err != nil {
		return Run{}, notFound("run "+id, err)
	}
	return run(row.Run, row.Harness, row.HarnessVersion), nil
}

// Conversation returns the runs of the conversation that the run with the
// given ID in workspace belongs to, oldest first. A run of another workspace
// is not found.
func (s *Store) Conversation(ctx context.Context, workspace, id string) ([]Run, error) {
	rows, err := s.queries.ConversationRuns(ctx, db.ConversationRunsParams{Workspace: workspace, ID: id})
	switch {
	case err != nil:
		return nil, fmt.Errorf("store: conversation of run %s: %w", id, err)
	case len(rows) == 0:
		return nil, fmt.Errorf("store: run %s: %w", id, ErrNotFound)
	}
	out := make([]Run, len(rows))
	for i, row := range rows {
		out[i] = run(row.Run, row.Harness, row.HarnessVersion)
	}
	return out, nil
}

// OwnRun returns the run with the given ID in workspace, if user started its
// conversation. Anyone else's run, as one of another workspace, is not
// found.
func (s *Store) OwnRun(ctx context.Context, workspace, user, id string) (Run, error) {
	row, err := s.queries.GetOwnRun(ctx, db.GetOwnRunParams{ID: id, Workspace: workspace, Owner: user})
	if err != nil {
		return Run{}, notFound("run "+id, err)
	}
	return run(row.Run, row.Harness, row.HarnessVersion), nil
}

// AuditRun is a run as auditors see it, with its workspace.
type AuditRun struct {
	Run
	Workspace string
}

// RunFilter selects runs to list.
type RunFilter struct {
	// Workspace, Harness, StartedBy and Status, when set, select the runs of
	// that workspace or harness, started by that user, or with that status.
	Workspace string
	Harness   string
	StartedBy string
	Status    RunStatus
	// Before, when set, lists the runs after the run with that ID, in the
	// order AuditRuns returns them: a page after one ending with that run.
	Before string
	// Limit is the most runs to return; it must be greater than 0.
	Limit int
}

// AuditRuns lists the runs of every workspace that f selects, newest first.
// Only auditors may see them.
func (s *Store) AuditRuns(ctx context.Context, f RunFilter) ([]AuditRun, error) {
	if f.Limit <= 0 || f.Limit > math.MaxInt32 {
		return nil, fmt.Errorf("store: runs: limit %d is out of range", f.Limit)
	}
	rows, err := s.queries.ListAuditRuns(ctx, db.ListAuditRunsParams{
		Workspace: optional(f.Workspace),
		Harness:   optional(f.Harness),
		StartedBy: optional(f.StartedBy),
		Status:    optional(string(f.Status)),
		Before:    optional(f.Before),
		MaxRows:   int32(f.Limit),
	})
	if err != nil {
		return nil, fmt.Errorf("store: runs: %w", err)
	}
	out := make([]AuditRun, len(rows))
	for i, row := range rows {
		out[i] = AuditRun{Run: run(row.Run, row.Harness, row.HarnessVersion), Workspace: row.Workspace}
	}
	return out, nil
}

// AuditRun returns the run with the given ID, of any workspace. Only
// auditors may see it.
func (s *Store) AuditRun(ctx context.Context, id string) (AuditRun, error) {
	row, err := s.queries.GetAuditRun(ctx, id)
	if err != nil {
		return AuditRun{}, notFound("run "+id, err)
	}
	return AuditRun{Run: run(row.Run, row.Harness, row.HarnessVersion), Workspace: row.Workspace}, nil
}

// ConversationSummary is a conversation as a list shows it, named by the ID
// of its first run.
type ConversationSummary struct {
	ID        string
	Workspace string
	Harness   string
	// Title is the first run's input, cut to its first 100 characters.
	Title string
	// Status is the latest run's status.
	Status RunStatus
	// UpdatedAt is when the conversation's latest run was created. Only
	// Conversations sets it.
	UpdatedAt time.Time
}

// ConversationFilter selects conversations to list.
type ConversationFilter struct {
	// User started the conversations, in any workspace.
	User string
	// BeforeAt and BeforeID, when BeforeID is set, list the conversations
	// after the one with that UpdatedAt and ID, in the order Conversations
	// returns them.
	BeforeAt time.Time
	BeforeID string
	// Limit is the most conversations to return; it must be greater than 0.
	Limit int
}

// Conversations lists the conversations f selects, latest activity first.
func (s *Store) Conversations(ctx context.Context, f ConversationFilter) ([]ConversationSummary, error) {
	if f.Limit <= 0 || f.Limit > math.MaxInt32 {
		return nil, fmt.Errorf("store: conversations: limit %d is out of range", f.Limit)
	}
	var before *time.Time
	if f.BeforeID != "" {
		before = &f.BeforeAt
	}
	rows, err := s.queries.ListConversations(ctx, db.ListConversationsParams{
		StartedBy: f.User,
		BeforeID:  optional(f.BeforeID),
		BeforeAt:  before,
		MaxRows:   int32(f.Limit),
	})
	if err != nil {
		return nil, fmt.Errorf("store: conversations: %w", err)
	}
	out := make([]ConversationSummary, len(rows))
	for i, row := range rows {
		out[i] = ConversationSummary{
			ID:        row.ID,
			Workspace: row.Workspace,
			Harness:   row.Harness,
			Title:     row.Title,
			Status:    RunStatus(row.Status),
			UpdatedAt: row.UpdatedAt,
		}
	}
	return out, nil
}

// FindConversation returns the conversation named by id, if user started it,
// in any workspace. A later run of a conversation does not name it.
func (s *Store) FindConversation(ctx context.Context, user, id string) (ConversationSummary, error) {
	row, err := s.queries.FindConversation(ctx, db.FindConversationParams{ID: id, StartedBy: user})
	if err != nil {
		return ConversationSummary{}, notFound("conversation "+id, err)
	}
	return ConversationSummary{ID: row.ID, Workspace: row.Workspace, Harness: row.Harness, Title: row.Title, Status: RunStatus(row.Status)}, nil
}

// optional is s as a nullable query argument: empty is NULL.
func optional(s string) pgtype.Text {
	return pgtype.Text{String: s, Valid: s != ""}
}

func run(row db.Run, harness string, version int32) Run {
	return Run{
		ID:               row.ID,
		HarnessVersionID: row.HarnessVersionID,
		Harness:          harness,
		HarnessVersion:   int(version),
		StartedBy:        row.StartedBy,
		Input:            row.Input,
		Status:           RunStatus(row.Status),
		Output:           row.Output,
		Steps:            int(row.Steps),
		Error:            row.Error,
		CreatedAt:        row.CreatedAt,
		FinishedAt:       row.FinishedAt,
		ConversationID:   row.ConversationID,
		Follows:          row.Follows.String,
		PromptDigest:     row.PromptDigest,
		HistoryDigest:    row.HistoryDigest,
		Usage: model.Usage{
			InputTokens:      row.InputTokens,
			OutputTokens:     row.OutputTokens,
			CacheWriteTokens: row.CacheWriteTokens,
			CacheReadTokens:  row.CacheReadTokens,
		},
	}
}

// FailRunningRuns marks every run that is still running as failed with
// reason, and returns how many it marked. A server calls it on startup: a
// run cannot outlive the process that ran it.
func (s *Store) FailRunningRuns(ctx context.Context, reason string) (int64, error) {
	var n int64
	_, err := s.withEvents(ctx, func(q *db.Queries) ([]auditlog.Event, error) {
		failed, err := q.FailRunningRuns(ctx, reason)
		if err != nil {
			return nil, fmt.Errorf("store: %w", err)
		}
		n = int64(len(failed))
		events := make([]auditlog.Event, len(failed))
		for i, r := range failed {
			events[i] = runFinished(r.Workspace, r.ID, RunFailed, r.Steps, reason)
		}
		return events, nil
	})
	return n, err
}

// text makes s storable in a text column, which accepts neither NUL bytes
// nor invalid UTF-8: both become U+FFFD.
func text(s string) string {
	return strings.ReplaceAll(strings.ToValidUTF8(s, "\uFFFD"), "\x00", "\uFFFD")
}

// jsonText makes raw storable in a json column: empty stays NULL, invalid
// UTF-8 becomes U+FFFD, and anything that is then still not valid JSON, such
// as text with a raw NUL byte, becomes a JSON string, where json.Marshal
// escapes the NUL.
func jsonText(raw json.RawMessage) []byte {
	if len(raw) == 0 {
		return nil
	}
	valid := []byte(strings.ToValidUTF8(string(raw), "\uFFFD"))
	if json.Valid(valid) {
		return valid
	}
	return must.Value(json.Marshal(string(valid)))
}

func notFound(what string, err error) error {
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("store: %s: %w", what, ErrNotFound)
	}
	return fmt.Errorf("store: %s: %w", what, err)
}

// TranscriptMessage is a stored message of a run's transcript.
type TranscriptMessage struct {
	// Position is the message's index in the run's conversation.
	Position int
	model.Message
	// Altered is set for a message stored other than as the model saw or
	// wrote it.
	Altered   bool
	CreatedAt time.Time
}

// NewMessage is a message to append to a run's transcript.
type NewMessage struct {
	// Position is the message's index in the run's conversation.
	Position int
	Message  model.Message
	// Altered says that Message is not as the model saw or wrote it, for
	// example because secrets were redacted from it.
	Altered bool
}

// AppendMessage stores m in the transcript of the run runID, which must
// exist, and adds its usage to the run's. A position is written once. As
// with Record, content never makes storing fail: invalid UTF-8 and NUL bytes
// in the text are replaced, and tool call arguments and provider parts that
// are not valid JSON are kept as a JSON string; a message changed so is
// stored as altered. A provider part's JSON is otherwise kept as written, so
// the provider can replay it exactly. A usage of all zeros is read back as
// none.
func (s *Store) AppendMessage(ctx context.Context, runID string, m NewMessage) error {
	msg, position := m.Message, m.Position
	altered := m.Altered || text(msg.Text) != msg.Text
	for _, r := range msg.ToolResults {
		altered = altered || !utf8.ValidString(r.Content)
	}
	calls := make([]model.ToolCall, len(msg.ToolCalls))
	for i, c := range msg.ToolCalls {
		c.Args = jsonText(c.Args)
		altered = altered || !bytes.Equal(c.Args, msg.ToolCalls[i].Args)
		calls[i] = c
	}
	var provider string
	var providerData []byte
	if p := msg.Provider; p != nil {
		if p.Name == "" {
			return fmt.Errorf("store: run %s: message %d: provider part without a name", runID, position)
		}
		provider, providerData = text(p.Name), jsonText(p.Data)
		altered = altered || !bytes.Equal(providerData, p.Data)
	}
	params := db.InsertRunMessageParams{
		RunID:        text(runID),
		Position:     int32(position), //nolint:gosec // G115: a position is bounded by the harness's max_steps.
		Role:         text(string(msg.Role)),
		Text:         text(msg.Text),
		ToolCalls:    jsonList(calls),
		ToolResults:  jsonList(msg.ToolResults),
		Provider:     provider,
		ProviderData: providerData,
		Altered:      altered,
	}
	if u := msg.Usage; u != nil {
		params.InputTokens, params.OutputTokens = u.InputTokens, u.OutputTokens
		params.CacheWriteTokens, params.CacheReadTokens = u.CacheWriteTokens, u.CacheReadTokens
	}
	err := s.queries.InsertRunMessage(ctx, params)
	if err != nil {
		return fmt.Errorf("store: run %s: message %d: %w", runID, position, err)
	}
	return nil
}

// jsonList encodes a list for a json column; an empty list stays NULL.
// json.Marshal replaces invalid UTF-8 and escapes NUL, which json accepts.
func jsonList[T any](list []T) []byte {
	if len(list) == 0 {
		return nil
	}
	return must.Value(json.Marshal(list))
}

// Transcript returns the stored transcript of a run, in order. A run without
// messages, or one that does not exist, has an empty transcript.
func (s *Store) Transcript(ctx context.Context, runID string) ([]TranscriptMessage, error) {
	rows, err := s.queries.RunMessages(ctx, runID)
	if err != nil {
		return nil, fmt.Errorf("store: run %s: transcript: %w", runID, err)
	}
	out := make([]TranscriptMessage, len(rows))
	for i, row := range rows {
		msg := model.Message{Role: model.Role(row.Role), Text: row.Text}
		if row.ToolCalls != nil {
			if err := json.Unmarshal(row.ToolCalls, &msg.ToolCalls); err != nil {
				return nil, fmt.Errorf("store: run %s: message %d: tool calls: %w", runID, row.Position, err)
			}
		}
		if row.ToolResults != nil {
			if err := json.Unmarshal(row.ToolResults, &msg.ToolResults); err != nil {
				return nil, fmt.Errorf("store: run %s: message %d: tool results: %w", runID, row.Position, err)
			}
		}
		if row.Provider != "" {
			msg.Provider = &model.ProviderPart{Name: row.Provider, Data: row.ProviderData}
		}
		if u := (model.Usage{InputTokens: row.InputTokens, OutputTokens: row.OutputTokens, CacheWriteTokens: row.CacheWriteTokens, CacheReadTokens: row.CacheReadTokens}); u != (model.Usage{}) {
			msg.Usage = &u
		}
		out[i] = TranscriptMessage{Position: int(row.Position), Message: msg, Altered: row.Altered, CreatedAt: row.CreatedAt}
	}
	return out, nil
}
