// Package store keeps Agenty's state in PostgreSQL: harness versions, runs,
// and the audit log. Queries are generated by sqlc from queries/ into db/;
// the schema lives in migrations/ and is applied by Open.
package store

//go:generate go run github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1 generate -f ../../sqlc.yaml

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"github.com/jangraefen/agenty/internal/harness"
	"github.com/jangraefen/agenty/internal/must"
	"github.com/jangraefen/agenty/internal/store/db"
	"github.com/jangraefen/agenty/internal/toolgateway"
)

//go:embed migrations/*.sql
var migrations embed.FS

// ErrNotFound is returned when a harness or run does not exist.
var ErrNotFound = errors.New("not found")

// Store is Agenty's state in PostgreSQL.
type Store struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

// Open connects to the database at url and applies every migration it has
// not applied yet. Close the Store to close its connections.
func Open(ctx context.Context, url string) (*Store, error) {
	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}
	if err := migrate(ctx, pool); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: migrate: %w", err)
	}
	return &Store{pool: pool, queries: db.New(pool)}, nil
}

func migrate(ctx context.Context, pool *pgxpool.Pool) error {
	sqlDB := stdlib.OpenDBFromPool(pool)
	provider, err := goose.NewProvider(goose.DialectPostgres, sqlDB, must.Value(fs.Sub(migrations, "migrations")))
	if err != nil {
		return errors.Join(err, sqlDB.Close())
	}
	_, err = provider.Up(ctx)
	return errors.Join(err, sqlDB.Close())
}

// Close closes the database connections.
func (s *Store) Close() {
	s.pool.Close()
}

// HarnessVersion is one stored version of a harness.
type HarnessVersion struct {
	// ID identifies the version across all harnesses; runs refer to it.
	ID        int64
	Version   int
	Harness   harness.Harness
	CreatedAt time.Time
}

// PutHarness stores h as the next version of its harness, after validating
// it. If h equals the latest version, nothing is stored and that version is
// returned, so applying an unchanged harness is a no-op.
func (s *Store) PutHarness(ctx context.Context, h harness.Harness) (HarnessVersion, error) {
	if err := h.Validate(); err != nil {
		return HarnessVersion{}, fmt.Errorf("store: invalid harness: %w", err)
	}
	definition := must.Value(json.Marshal(h))

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return HarnessVersion{}, fmt.Errorf("store: %w", err)
	}
	q := s.queries.WithTx(tx)
	next := int32(1)
	latest, err := q.LatestHarnessVersion(ctx, h.Name)
	switch {
	case errors.Is(err, pgx.ErrNoRows):
	case err != nil:
		return HarnessVersion{}, errors.Join(fmt.Errorf("store: %w", err), tx.Rollback(ctx))
	default:
		v, err := harnessVersion(latest)
		if err != nil {
			return HarnessVersion{}, errors.Join(err, tx.Rollback(ctx))
		}
		if bytes.Equal(must.Value(json.Marshal(v.Harness)), definition) {
			return v, tx.Rollback(ctx)
		}
		next = latest.Version + 1
	}
	row, err := q.InsertHarnessVersion(ctx, db.InsertHarnessVersionParams{Name: h.Name, Version: next, Definition: definition})
	if err != nil {
		return HarnessVersion{}, errors.Join(fmt.Errorf("store: %w", err), tx.Rollback(ctx))
	}
	if err := tx.Commit(ctx); err != nil {
		return HarnessVersion{}, fmt.Errorf("store: %w", err)
	}
	return harnessVersion(row)
}

// Harness returns the latest version of the named harness.
func (s *Store) Harness(ctx context.Context, name string) (HarnessVersion, error) {
	row, err := s.queries.LatestHarnessVersion(ctx, name)
	if err != nil {
		return HarnessVersion{}, notFound("harness "+name, err)
	}
	return harnessVersion(row)
}

// HarnessVersionByID returns the harness version with the given ID.
func (s *Store) HarnessVersionByID(ctx context.Context, id int64) (HarnessVersion, error) {
	row, err := s.queries.HarnessVersionByID(ctx, id)
	if err != nil {
		return HarnessVersion{}, notFound(fmt.Sprintf("harness version %d", id), err)
	}
	return harnessVersion(row)
}

// Harnesses returns the latest version of every harness, sorted by name.
func (s *Store) Harnesses(ctx context.Context) ([]HarnessVersion, error) {
	rows, err := s.queries.LatestHarnessVersions(ctx)
	if err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}
	out := make([]HarnessVersion, 0, len(rows))
	for _, row := range rows {
		v, err := harnessVersion(row)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, nil
}

func harnessVersion(row db.HarnessVersion) (HarnessVersion, error) {
	var h harness.Harness
	if err := json.Unmarshal(row.Definition, &h); err != nil {
		return HarnessVersion{}, fmt.Errorf("store: harness %s version %d: %w", row.Name, row.Version, err)
	}
	return HarnessVersion{ID: row.ID, Version: int(row.Version), Harness: h, CreatedAt: row.CreatedAt}, nil
}

// RunStatus is the state of a run.
type RunStatus string

const (
	RunRunning   RunStatus = "running"
	RunSucceeded RunStatus = "succeeded"
	RunFailed    RunStatus = "failed"
)

// Run is a stored run.
type Run struct {
	ID               string
	HarnessVersionID int64
	Input            string
	Status           RunStatus
	Output           string
	Steps            int
	Error            string
	CreatedAt        time.Time
	// FinishedAt is nil while the run is running.
	FinishedAt *time.Time
}

// CreateRun stores a new running run of the given harness version.
func (s *Store) CreateRun(ctx context.Context, id string, harnessVersionID int64, input string) error {
	if err := s.queries.InsertRun(ctx, db.InsertRunParams{ID: id, HarnessVersionID: harnessVersionID, Input: input}); err != nil {
		return fmt.Errorf("store: run %s: %w", id, err)
	}
	return nil
}

// FinishRun records the end of a running run. Finishing a run that does not
// exist or has already finished returns ErrNotFound.
func (s *Store) FinishRun(ctx context.Context, id string, status RunStatus, output string, steps int, runErr string) error {
	if status == RunRunning {
		return fmt.Errorf("store: run %s: cannot finish as %s", id, status)
	}
	n, err := s.queries.FinishRun(ctx, db.FinishRunParams{ID: id, Status: string(status), Output: output, Steps: int32(steps), Error: runErr}) //nolint:gosec // G115: steps is bounded by the harness's max_steps.
	switch {
	case err != nil:
		return fmt.Errorf("store: run %s: %w", id, err)
	case n == 0:
		return fmt.Errorf("store: running run %s: %w", id, ErrNotFound)
	}
	return nil
}

// Run returns the run with the given ID.
func (s *Store) Run(ctx context.Context, id string) (Run, error) {
	row, err := s.queries.GetRun(ctx, id)
	if err != nil {
		return Run{}, notFound("run "+id, err)
	}
	return Run{
		ID:               row.ID,
		HarnessVersionID: row.HarnessVersionID,
		Input:            row.Input,
		Status:           RunStatus(row.Status),
		Output:           row.Output,
		Steps:            int(row.Steps),
		Error:            row.Error,
		CreatedAt:        row.CreatedAt,
		FinishedAt:       row.FinishedAt,
	}, nil
}

// FailRunningRuns marks every run that is still running as failed with
// reason, and returns how many it marked. A server calls it on startup: a
// run cannot outlive the process that ran it.
func (s *Store) FailRunningRuns(ctx context.Context, reason string) (int64, error) {
	n, err := s.queries.FailRunningRuns(ctx, reason)
	if err != nil {
		return 0, fmt.Errorf("store: %w", err)
	}
	return n, nil
}

var _ toolgateway.Audit = (*Store)(nil)

// Record appends rec to the audit log. The record's run must exist. An error
// means the record may not be stored, and the gateway then does not execute
// the call.
func (s *Store) Record(ctx context.Context, rec toolgateway.Record) error {
	err := s.queries.InsertAuditRecord(ctx, db.InsertAuditRecordParams{
		RunID:    rec.RunID,
		CallID:   rec.CallID,
		Event:    string(rec.Event),
		Tool:     rec.Tool,
		Args:     jsonb(rec.Args),
		Decision: string(rec.Decision),
		Reason:   rec.Reason,
		Approver: rec.Approver,
		Result:   jsonb(rec.Result),
		Error:    rec.Err,
	})
	if err != nil {
		return fmt.Errorf("store: audit: %w", err)
	}
	return nil
}

// AuditRecord is a stored audit record.
type AuditRecord struct {
	toolgateway.Record
	RecordedAt time.Time
}

// AuditRecords returns the audit records of a run, in the order they were
// recorded.
func (s *Store) AuditRecords(ctx context.Context, runID string) ([]AuditRecord, error) {
	rows, err := s.queries.AuditRecordsOfRun(ctx, runID)
	if err != nil {
		return nil, fmt.Errorf("store: audit: %w", err)
	}
	out := make([]AuditRecord, len(rows))
	for i, row := range rows {
		out[i] = AuditRecord{
			Record: toolgateway.Record{
				RunID:    row.RunID,
				CallID:   row.CallID,
				Event:    toolgateway.Event(row.Event),
				Tool:     row.Tool,
				Args:     row.Args,
				Decision: toolgateway.Decision(row.Decision),
				Reason:   row.Reason,
				Approver: row.Approver,
				Result:   row.Result,
				Err:      row.Error,
			},
			RecordedAt: row.RecordedAt,
		}
	}
	return out, nil
}

// jsonb prepares raw JSON for a jsonb column: empty stays NULL, and anything
// that is not valid JSON, such as malformed arguments from a model, is stored
// as a JSON string, so that recording never fails on content.
func jsonb(raw json.RawMessage) []byte {
	switch {
	case len(raw) == 0:
		return nil
	case json.Valid(raw):
		return raw
	default:
		return must.Value(json.Marshal(string(raw)))
	}
}

func notFound(what string, err error) error {
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("store: %s: %w", what, ErrNotFound)
	}
	return fmt.Errorf("store: %s: %w", what, err)
}
