// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package db

import (
	"context"
	"time"
)

const answerApproval = `-- name: AnswerApproval :one
UPDATE approvals
SET status = $1, approver = $2, reason = $3, answered_at = now()
FROM runs, harness_versions
WHERE approvals.id = $4 AND approvals.run_id = $5
  AND runs.id = approvals.run_id AND harness_versions.id = runs.harness_version_id
  AND harness_versions.workspace = $6
  AND approvals.status = 'pending' AND approvals.expires_at > now()
RETURNING approvals.run_id
`

type AnswerApprovalParams struct {
	Status    string
	Approver  string
	Reason    string
	ID        string
	RunID     string
	Workspace string
}

// Answers a pending, unexpired request of a run of the workspace, and
// returns its run.
func (q *Queries) AnswerApproval(ctx context.Context, arg AnswerApprovalParams) (string, error) {
	row := q.db.QueryRow(ctx, answerApproval,
		arg.Status,
		arg.Approver,
		arg.Reason,
		arg.ID,
		arg.RunID,
		arg.Workspace,
	)
	var run_id string
	err := row.Scan(&run_id)
	return run_id, err
}

const expireApprovals = `-- name: ExpireApprovals :many
UPDATE approvals
SET status = 'rejected', reason = $1, answered_at = now()
WHERE status = 'pending' AND expires_at <= now()
RETURNING run_id
`

// Rejects the pending requests that have expired, and returns their runs.
func (q *Queries) ExpireApprovals(ctx context.Context, reason string) ([]string, error) {
	rows, err := q.db.Query(ctx, expireApprovals, reason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var run_id string
		if err := rows.Scan(&run_id); err != nil {
			return nil, err
		}
		items = append(items, run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertApproval = `-- name: InsertApproval :exec
INSERT INTO approvals (id, run_id, call_id, call_index, tool, args, reasons, results, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertApprovalParams struct {
	ID        string
	RunID     string
	CallID    string
	CallIndex int32
	Tool      string
	Args      []byte
	Reasons   []byte
	Results   []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) error {
	_, err := q.db.Exec(ctx, insertApproval,
		arg.ID,
		arg.RunID,
		arg.CallID,
		arg.CallIndex,
		arg.Tool,
		arg.Args,
		arg.Reasons,
		arg.Results,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const latestApproval = `-- name: LatestApproval :one
SELECT approvals.id, approvals.run_id, approvals.call_id, approvals.call_index, approvals.tool, approvals.args, approvals.reasons, approvals.results, approvals.status, approvals.approver, approvals.reason, approvals.created_at, approvals.expires_at, approvals.answered_at, harness_versions.name AS harness
FROM approvals
JOIN runs ON runs.id = approvals.run_id
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE approvals.run_id = $1
ORDER BY approvals.created_at DESC, approvals.id DESC
LIMIT 1
`

type LatestApprovalRow struct {
	Approval Approval
	Harness  string
}

// The latest approval request of a run, with its harness.
func (q *Queries) LatestApproval(ctx context.Context, runID string) (LatestApprovalRow, error) {
	row := q.db.QueryRow(ctx, latestApproval, runID)
	var i LatestApprovalRow
	err := row.Scan(
		&i.Approval.ID,
		&i.Approval.RunID,
		&i.Approval.CallID,
		&i.Approval.CallIndex,
		&i.Approval.Tool,
		&i.Approval.Args,
		&i.Approval.Reasons,
		&i.Approval.Results,
		&i.Approval.Status,
		&i.Approval.Approver,
		&i.Approval.Reason,
		&i.Approval.CreatedAt,
		&i.Approval.ExpiresAt,
		&i.Approval.AnsweredAt,
		&i.Harness,
	)
	return i, err
}

const nextApprovalExpiry = `-- name: NextApprovalExpiry :one
SELECT expires_at FROM approvals WHERE status = 'pending'
ORDER BY expires_at
LIMIT 1
`

func (q *Queries) NextApprovalExpiry(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, nextApprovalExpiry)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const pendingApprovals = `-- name: PendingApprovals :many
SELECT approvals.id, approvals.run_id, approvals.call_id, approvals.call_index, approvals.tool, approvals.args, approvals.reasons, approvals.results, approvals.status, approvals.approver, approvals.reason, approvals.created_at, approvals.expires_at, approvals.answered_at, harness_versions.name AS harness
FROM approvals
JOIN runs ON runs.id = approvals.run_id
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE harness_versions.workspace = $1 AND approvals.status = 'pending'
ORDER BY approvals.created_at, approvals.id
`

type PendingApprovalsRow struct {
	Approval Approval
	Harness  string
}

// The waiting approval requests of a workspace, oldest first.
func (q *Queries) PendingApprovals(ctx context.Context, workspace string) ([]PendingApprovalsRow, error) {
	rows, err := q.db.Query(ctx, pendingApprovals, workspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingApprovalsRow
	for rows.Next() {
		var i PendingApprovalsRow
		if err := rows.Scan(
			&i.Approval.ID,
			&i.Approval.RunID,
			&i.Approval.CallID,
			&i.Approval.CallIndex,
			&i.Approval.Tool,
			&i.Approval.Args,
			&i.Approval.Reasons,
			&i.Approval.Results,
			&i.Approval.Status,
			&i.Approval.Approver,
			&i.Approval.Reason,
			&i.Approval.CreatedAt,
			&i.Approval.ExpiresAt,
			&i.Approval.AnsweredAt,
			&i.Harness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueWaitingRuns = `-- name: QueueWaitingRuns :execrows
UPDATE runs SET status = 'queued'
WHERE id = ANY($1::text[]) AND status = 'waiting'
`

func (q *Queries) QueueWaitingRuns(ctx context.Context, ids []string) (int64, error) {
	result, err := q.db.Exec(ctx, queueWaitingRuns, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suspendRun = `-- name: SuspendRun :execrows
UPDATE runs SET status = 'waiting'
WHERE id = $1 AND status = 'running'
`

func (q *Queries) SuspendRun(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, suspendRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const withdrawApprovals = `-- name: WithdrawApprovals :exec
UPDATE approvals
SET status = 'withdrawn', reason = $2, answered_at = now()
WHERE run_id = $1 AND status = 'pending'
`

type WithdrawApprovalsParams struct {
	RunID  string
	Reason string
}

func (q *Queries) WithdrawApprovals(ctx context.Context, arg WithdrawApprovalsParams) error {
	_, err := q.db.Exec(ctx, withdrawApprovals, arg.RunID, arg.Reason)
	return err
}
