// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditEventsAfter = `-- name: AuditEventsAfter :many
SELECT id, recorded_at, actor, action, workspace, run_id, target, details, prev_hash, hash FROM audit_events WHERE id > $1 AND id <= $2 ORDER BY id LIMIT $3
`

type AuditEventsAfterParams struct {
	After   int64
	Last    int64
	MaxRows int32
}

// The events after the one with the given id up to the one with the last,
// in order, a page at a time. last is fixed when an export starts, so it
// ends at that event however many are appended while it streams.
func (q *Queries) AuditEventsAfter(ctx context.Context, arg AuditEventsAfterParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, auditEventsAfter, arg.After, arg.Last, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Actor,
			&i.Action,
			&i.Workspace,
			&i.RunID,
			&i.Target,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, recorded_at, actor, action, workspace, run_id, target, details, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditEventParams struct {
	ID         int64
	RecordedAt time.Time
	Actor      string
	Action     string
	Workspace  string
	RunID      pgtype.Text
	Target     string
	Details    []byte
	PrevHash   []byte
	Hash       []byte
}

// Inserts an event whose id, previous hash and hash the store computed
// holding LockAuditLog. The primary key would refuse a second event with
// the same id, should the lock ever be bypassed.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.RecordedAt,
		arg.Actor,
		arg.Action,
		arg.Workspace,
		arg.RunID,
		arg.Target,
		arg.Details,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const lastAuditEvent = `-- name: LastAuditEvent :one
SELECT id, hash FROM audit_events ORDER BY id DESC LIMIT 1
`

type LastAuditEventRow struct {
	ID   int64
	Hash []byte
}

// The latest event's id and hash; an append calls it holding the lock.
func (q *Queries) LastAuditEvent(ctx context.Context) (LastAuditEventRow, error) {
	row := q.db.QueryRow(ctx, lastAuditEvent)
	var i LastAuditEventRow
	err := row.Scan(&i.ID, &i.Hash)
	return i, err
}

const listActorEvents = `-- name: ListActorEvents :many
SELECT id, recorded_at, actor, action, workspace, run_id, target, details, prev_hash, hash FROM audit_events
WHERE actor = $1
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListActorEventsParams struct {
	Actor   string
	Before  int64
	MaxRows int32
}

// What actor did, newest first, before the event named by before (0 for
// the newest). A user's own activity; served by audit_events_actor.
func (q *Queries) ListActorEvents(ctx context.Context, arg ListActorEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listActorEvents, arg.Actor, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Actor,
			&i.Action,
			&i.Workspace,
			&i.RunID,
			&i.Target,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, recorded_at, actor, action, workspace, run_id, target, details, prev_hash, hash FROM audit_events
WHERE ($1::text IS NULL OR actor = $1)
  AND ($2::text IS NULL OR workspace = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::text IS NULL OR run_id = $4)
  AND ($5::bigint IS NULL OR id < $5)
ORDER BY id DESC
LIMIT $6
`

type ListAuditEventsParams struct {
	Actor     pgtype.Text
	Workspace pgtype.Text
	Action    pgtype.Text
	RunID     pgtype.Text
	Before    pgtype.Int8
	MaxRows   int32
}

// For auditors only.
// The events of the audit log, newest first, before the one named by before
// when set, optionally by one actor, in one workspace, with one action, or
// about one run. A NULL argument matches every event, so one query serves
// every combination of filters.
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.Actor,
		arg.Workspace,
		arg.Action,
		arg.RunID,
		arg.Before,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Actor,
			&i.Action,
			&i.Workspace,
			&i.RunID,
			&i.Target,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceEvents = `-- name: ListWorkspaceEvents :many
SELECT id, recorded_at, actor, action, workspace, run_id, target, details, prev_hash, hash FROM audit_events
WHERE workspace = $1 AND action = $2
  AND ($3::bigint = 0 OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListWorkspaceEventsParams struct {
	Workspace string
	Action    string
	Before    int64
	MaxRows   int32
}

// The events of a workspace with an action, newest first, before the event
// named by before (0 for the newest). A workspace's changes for its
// members; served by audit_events_workspace_action.
func (q *Queries) ListWorkspaceEvents(ctx context.Context, arg ListWorkspaceEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listWorkspaceEvents,
		arg.Workspace,
		arg.Action,
		arg.Before,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Actor,
			&i.Action,
			&i.Workspace,
			&i.RunID,
			&i.Target,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuditLog = `-- name: LockAuditLog :exec
SELECT pg_advisory_xact_lock(hashtext('agenty'), hashtext('audit log'))
`

// Serialises appends to the audit log until the transaction ends, so its
// chain stays linear. Its two keys keep it apart from the one-key locks,
// such as LockHarnessName's.
func (q *Queries) LockAuditLog(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAuditLog)
	return err
}

const runEventsAfter = `-- name: RunEventsAfter :many
SELECT id, action, details, recorded_at FROM audit_events
WHERE run_id = $1
  AND action IN ('tool.decision', 'tool.approval', 'tool.result', 'approval.requested', 'run.finished')
  AND id > $2
ORDER BY id
LIMIT $3
`

type RunEventsAfterParams struct {
	RunID   pgtype.Text
	After   int64
	MaxRows int32
}

type RunEventsAfterRow struct {
	ID         int64
	Action     string
	Details    []byte
	RecordedAt time.Time
}

// A run's event stream after the event with the given id, in order, a page
// at a time: the tool gateway's records, its approval requests and its end.
func (q *Queries) RunEventsAfter(ctx context.Context, arg RunEventsAfterParams) ([]RunEventsAfterRow, error) {
	rows, err := q.db.Query(ctx, runEventsAfter, arg.RunID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunEventsAfterRow
	for rows.Next() {
		var i RunEventsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Details,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runOwner = `-- name: RunOwner :one
SELECT runs.started_by, harness_versions.workspace
FROM runs
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE runs.id = $1
`

type RunOwnerRow struct {
	StartedBy string
	Workspace string
}

// Who started the run, and in which workspace, for its events. No row for
// a run that is not stored, which makes recording for it fail.
func (q *Queries) RunOwner(ctx context.Context, id string) (RunOwnerRow, error) {
	row := q.db.QueryRow(ctx, runOwner, id)
	var i RunOwnerRow
	err := row.Scan(&i.StartedBy, &i.Workspace)
	return i, err
}

const toolEventsOfRun = `-- name: ToolEventsOfRun :many
SELECT action, details, recorded_at FROM audit_events
WHERE run_id = $1 AND action IN ('tool.decision', 'tool.approval', 'tool.result')
ORDER BY id
`

type ToolEventsOfRunRow struct {
	Action     string
	Details    []byte
	RecordedAt time.Time
}

// What the tool gateway recorded for a run, in order. Uses the partial
// index audit_events_run_id.
func (q *Queries) ToolEventsOfRun(ctx context.Context, runID pgtype.Text) ([]ToolEventsOfRunRow, error) {
	rows, err := q.db.Query(ctx, toolEventsOfRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolEventsOfRunRow
	for rows.Next() {
		var i ToolEventsOfRunRow
		if err := rows.Scan(&i.Action, &i.Details, &i.RecordedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
