// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"
)

const auditRecordsOfRun = `-- name: AuditRecordsOfRun :many
SELECT id, run_id, call_id, event, tool, args, decision, reason, approver, result, error, recorded_at FROM audit_records
WHERE run_id = $1
ORDER BY id
`

func (q *Queries) AuditRecordsOfRun(ctx context.Context, runID string) ([]AuditRecord, error) {
	rows, err := q.db.Query(ctx, auditRecordsOfRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditRecord
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.CallID,
			&i.Event,
			&i.Tool,
			&i.Args,
			&i.Decision,
			&i.Reason,
			&i.Approver,
			&i.Result,
			&i.Error,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditRecord = `-- name: InsertAuditRecord :one
INSERT INTO audit_records (run_id, call_id, event, tool, args, decision, reason, approver, result, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING recorded_at
`

type InsertAuditRecordParams struct {
	RunID    string
	CallID   string
	Event    string
	Tool     string
	Args     []byte
	Decision string
	Reason   string
	Approver string
	Result   []byte
	Error    string
}

func (q *Queries) InsertAuditRecord(ctx context.Context, arg InsertAuditRecordParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertAuditRecord,
		arg.RunID,
		arg.CallID,
		arg.Event,
		arg.Tool,
		arg.Args,
		arg.Decision,
		arg.Reason,
		arg.Approver,
		arg.Result,
		arg.Error,
	)
	var recorded_at time.Time
	err := row.Scan(&recorded_at)
	return recorded_at, err
}
