// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: harnesses.sql

package db

import (
	"context"
)

const harnessVersionByID = `-- name: HarnessVersionByID :one
SELECT id, name, version, definition, created_at FROM harness_versions
WHERE id = $1
`

func (q *Queries) HarnessVersionByID(ctx context.Context, id int64) (HarnessVersion, error) {
	row := q.db.QueryRow(ctx, harnessVersionByID, id)
	var i HarnessVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
	)
	return i, err
}

const insertHarnessVersion = `-- name: InsertHarnessVersion :one
INSERT INTO harness_versions (name, version, definition)
VALUES ($1, $2, $3)
RETURNING id, name, version, definition, created_at
`

type InsertHarnessVersionParams struct {
	Name       string
	Version    int32
	Definition []byte
}

func (q *Queries) InsertHarnessVersion(ctx context.Context, arg InsertHarnessVersionParams) (HarnessVersion, error) {
	row := q.db.QueryRow(ctx, insertHarnessVersion, arg.Name, arg.Version, arg.Definition)
	var i HarnessVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
	)
	return i, err
}

const latestHarnessVersion = `-- name: LatestHarnessVersion :one
SELECT id, name, version, definition, created_at FROM harness_versions
WHERE name = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) LatestHarnessVersion(ctx context.Context, name string) (HarnessVersion, error) {
	row := q.db.QueryRow(ctx, latestHarnessVersion, name)
	var i HarnessVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
	)
	return i, err
}

const latestHarnessVersions = `-- name: LatestHarnessVersions :many
SELECT DISTINCT ON (name) id, name, version, definition, created_at FROM harness_versions
ORDER BY name, version DESC
`

func (q *Queries) LatestHarnessVersions(ctx context.Context) ([]HarnessVersion, error) {
	rows, err := q.db.Query(ctx, latestHarnessVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HarnessVersion
	for rows.Next() {
		var i HarnessVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Definition,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHarnessName = `-- name: LockHarnessName :exec
SELECT pg_advisory_xact_lock(hashtext($1))
`

// Serializes versioning of one harness name until the transaction ends.
func (q *Queries) LockHarnessName(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, lockHarnessName, hashtext)
	return err
}
