// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: harnesses.sql

package db

import (
	"context"
)

const harnessVersionByID = `-- name: HarnessVersionByID :one
SELECT id, name, version, definition, created_at, workspace FROM harness_versions
WHERE id = $1
`

func (q *Queries) HarnessVersionByID(ctx context.Context, id int64) (HarnessVersion, error) {
	row := q.db.QueryRow(ctx, harnessVersionByID, id)
	var i HarnessVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.Workspace,
	)
	return i, err
}

const insertHarnessVersion = `-- name: InsertHarnessVersion :one
INSERT INTO harness_versions (workspace, name, version, definition)
VALUES ($1, $2, $3, $4)
RETURNING id, name, version, definition, created_at, workspace
`

type InsertHarnessVersionParams struct {
	Workspace  string
	Name       string
	Version    int32
	Definition []byte
}

func (q *Queries) InsertHarnessVersion(ctx context.Context, arg InsertHarnessVersionParams) (HarnessVersion, error) {
	row := q.db.QueryRow(ctx, insertHarnessVersion,
		arg.Workspace,
		arg.Name,
		arg.Version,
		arg.Definition,
	)
	var i HarnessVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.Workspace,
	)
	return i, err
}

const latestHarnessVersion = `-- name: LatestHarnessVersion :one
SELECT id, name, version, definition, created_at, workspace FROM harness_versions
WHERE workspace = $1 AND name = $2
ORDER BY version DESC
LIMIT 1
`

type LatestHarnessVersionParams struct {
	Workspace string
	Name      string
}

func (q *Queries) LatestHarnessVersion(ctx context.Context, arg LatestHarnessVersionParams) (HarnessVersion, error) {
	row := q.db.QueryRow(ctx, latestHarnessVersion, arg.Workspace, arg.Name)
	var i HarnessVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.Workspace,
	)
	return i, err
}

const latestHarnessVersions = `-- name: LatestHarnessVersions :many
SELECT DISTINCT ON (name) id, name, version, definition, created_at, workspace FROM harness_versions
WHERE workspace = $1
ORDER BY name, version DESC
`

func (q *Queries) LatestHarnessVersions(ctx context.Context, workspace string) ([]HarnessVersion, error) {
	rows, err := q.db.Query(ctx, latestHarnessVersions, workspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HarnessVersion
	for rows.Next() {
		var i HarnessVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Definition,
			&i.CreatedAt,
			&i.Workspace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHarnessName = `-- name: LockHarnessName :exec
SELECT pg_advisory_xact_lock(hashtext($1))
`

// Serializes versioning of one harness until the transaction ends. The key
// is the workspace and harness name, joined by a character neither has.
func (q *Queries) LockHarnessName(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, lockHarnessName, hashtext)
	return err
}
