// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	ID         string
	RunID      string
	CallID     string
	CallIndex  int32
	Tool       string
	Args       []byte
	Reasons    []byte
	Results    []byte
	Status     string
	Approver   string
	Reason     string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	AnsweredAt *time.Time
}

type AuditRecord struct {
	ID         int64
	RunID      string
	CallID     string
	Event      string
	Tool       string
	Args       []byte
	Decision   string
	Reason     string
	Approver   string
	Result     []byte
	Error      string
	RecordedAt time.Time
}

type HarnessVersion struct {
	ID         int64
	Name       string
	Version    int32
	Definition []byte
	CreatedAt  time.Time
	Workspace  string
}

type Run struct {
	ID               string
	HarnessVersionID int64
	Input            string
	Status           string
	Output           string
	Steps            int32
	Error            string
	CreatedAt        time.Time
	FinishedAt       *time.Time
	StartedBy        string
	ConversationID   string
	Follows          pgtype.Text
	PromptDigest     string
	HistoryDigest    string
	InputTokens      int64
	OutputTokens     int64
	CacheWriteTokens int64
	CacheReadTokens  int64
}

type RunMessage struct {
	RunID            string
	Position         int32
	Role             string
	Text             string
	ToolCalls        []byte
	ToolResults      []byte
	CreatedAt        time.Time
	Provider         string
	ProviderData     []byte
	Altered          bool
	InputTokens      int64
	OutputTokens     int64
	CacheWriteTokens int64
	CacheReadTokens  int64
}
