// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	ID         string
	RunID      string
	CallID     string
	CallIndex  int32
	Tool       string
	Args       []byte
	Reasons    []byte
	Results    []byte
	Status     string
	Approver   string
	Reason     string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	AnsweredAt *time.Time
}

type AuditEvent struct {
	ID         int64
	RecordedAt time.Time
	Actor      string
	Action     string
	Workspace  string
	RunID      pgtype.Text
	Target     string
	Details    []byte
	PrevHash   []byte
	Hash       []byte
}

type HarnessVersion struct {
	ID         int64
	Workspace  string
	Name       string
	Version    int32
	Definition []byte
	CreatedAt  time.Time
}

type Run struct {
	ID               string
	HarnessVersionID int64
	Input            string
	StartedBy        string
	ConversationID   string
	Follows          pgtype.Text
	Status           string
	Output           string
	Steps            int32
	Error            string
	PromptDigest     string
	HistoryDigest    string
	InputTokens      int64
	OutputTokens     int64
	CacheWriteTokens int64
	CacheReadTokens  int64
	CreatedAt        time.Time
	FinishedAt       *time.Time
}

type RunMessage struct {
	RunID            string
	Position         int32
	Role             string
	Text             string
	ToolCalls        []byte
	ToolResults      []byte
	Provider         string
	ProviderData     []byte
	Altered          bool
	InputTokens      int64
	OutputTokens     int64
	CacheWriteTokens int64
	CacheReadTokens  int64
	CreatedAt        time.Time
}
