// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
)

const failRunningRuns = `-- name: FailRunningRuns :execrows
UPDATE runs
SET status = 'failed', error = $1, finished_at = now()
WHERE status = 'running'
`

func (q *Queries) FailRunningRuns(ctx context.Context, error string) (int64, error) {
	result, err := q.db.Exec(ctx, failRunningRuns, error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRun = `-- name: FinishRun :execrows
UPDATE runs
SET status = $2, output = $3, steps = $4, error = $5, finished_at = now()
WHERE id = $1 AND status = 'running'
`

type FinishRunParams struct {
	ID     string
	Status string
	Output string
	Steps  int32
	Error  string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.Steps,
		arg.Error,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRun = `-- name: GetRun :one
SELECT runs.id, runs.harness_version_id, runs.input, runs.status, runs.output, runs.steps, runs.error, runs.created_at, runs.finished_at, runs.started_by FROM runs
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE runs.id = $1 AND harness_versions.workspace = $2
`

type GetRunParams struct {
	ID        string
	Workspace string
}

// A run is found only in the workspace of the harness version it runs.
func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.Workspace)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.HarnessVersionID,
		&i.Input,
		&i.Status,
		&i.Output,
		&i.Steps,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.StartedBy,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO runs (id, harness_version_id, input, started_by)
VALUES ($1, $2, $3, $4)
`

type InsertRunParams struct {
	ID               string
	HarnessVersionID int64
	Input            string
	StartedBy        string
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.Exec(ctx, insertRun,
		arg.ID,
		arg.HarnessVersionID,
		arg.Input,
		arg.StartedBy,
	)
	return err
}
