// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelIdleRun = `-- name: CancelIdleRun :many
UPDATE runs
SET status = 'cancelled', error = $2, finished_at = now()
FROM harness_versions
WHERE runs.id = $1 AND runs.status IN ('queued', 'waiting') AND harness_versions.id = runs.harness_version_id
RETURNING runs.steps, harness_versions.workspace
`

type CancelIdleRunParams struct {
	ID    string
	Error string
}

type CancelIdleRunRow struct {
	Steps     int32
	Workspace string
}

func (q *Queries) CancelIdleRun(ctx context.Context, arg CancelIdleRunParams) ([]CancelIdleRunRow, error) {
	rows, err := q.db.Query(ctx, cancelIdleRun, arg.ID, arg.Error)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CancelIdleRunRow
	for rows.Next() {
		var i CancelIdleRunRow
		if err := rows.Scan(&i.Steps, &i.Workspace); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRun = `-- name: ClaimRun :one
WITH claimed AS (
    UPDATE runs
    SET status = 'running'
    WHERE status = 'queued' AND id = (
        SELECT q.id FROM runs q
        WHERE q.status = 'queued'
        ORDER BY q.created_at, q.id
        LIMIT 1
        FOR NO KEY UPDATE SKIP LOCKED)
    RETURNING runs.id, runs.harness_version_id
)
SELECT claimed.id, harness_versions.workspace
FROM claimed
JOIN harness_versions ON harness_versions.id = claimed.harness_version_id
`

type ClaimRunRow struct {
	ID        string
	Workspace string
}

// Marks the oldest queued run as running and returns it with its workspace.
// Concurrent claims skip each other's rows, so each run is claimed once.
func (q *Queries) ClaimRun(ctx context.Context) (ClaimRunRow, error) {
	row := q.db.QueryRow(ctx, claimRun)
	var i ClaimRunRow
	err := row.Scan(&i.ID, &i.Workspace)
	return i, err
}

const conversationRuns = `-- name: ConversationRuns :many
SELECT runs.id, runs.harness_version_id, runs.input, runs.started_by, runs.conversation_id, runs.follows, runs.status, runs.output, runs.steps, runs.error, runs.prompt_digest, runs.history_digest, runs.input_tokens, runs.output_tokens, runs.cache_write_tokens, runs.cache_read_tokens, runs.created_at, runs.finished_at, harness_versions.name AS harness, harness_versions.version AS harness_version
FROM runs
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE harness_versions.workspace = $1
  AND runs.conversation_id = (SELECT c.conversation_id FROM runs c WHERE c.id = $2)
ORDER BY runs.created_at, runs.id
`

type ConversationRunsParams struct {
	Workspace string
	ID        string
}

type ConversationRunsRow struct {
	Run            Run
	Harness        string
	HarnessVersion int32
}

// The runs of the conversation the run named by id belongs to, oldest first,
// if that run is one of the workspace's.
func (q *Queries) ConversationRuns(ctx context.Context, arg ConversationRunsParams) ([]ConversationRunsRow, error) {
	rows, err := q.db.Query(ctx, conversationRuns, arg.Workspace, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationRunsRow
	for rows.Next() {
		var i ConversationRunsRow
		if err := rows.Scan(
			&i.Run.ID,
			&i.Run.HarnessVersionID,
			&i.Run.Input,
			&i.Run.StartedBy,
			&i.Run.ConversationID,
			&i.Run.Follows,
			&i.Run.Status,
			&i.Run.Output,
			&i.Run.Steps,
			&i.Run.Error,
			&i.Run.PromptDigest,
			&i.Run.HistoryDigest,
			&i.Run.InputTokens,
			&i.Run.OutputTokens,
			&i.Run.CacheWriteTokens,
			&i.Run.CacheReadTokens,
			&i.Run.CreatedAt,
			&i.Run.FinishedAt,
			&i.Harness,
			&i.HarnessVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failRunningRuns = `-- name: FailRunningRuns :many
UPDATE runs
SET status = 'failed', error = $1, finished_at = now()
FROM harness_versions
WHERE runs.status = 'running' AND harness_versions.id = runs.harness_version_id
RETURNING runs.id, runs.steps, harness_versions.workspace
`

type FailRunningRunsRow struct {
	ID        string
	Steps     int32
	Workspace string
}

func (q *Queries) FailRunningRuns(ctx context.Context, error string) ([]FailRunningRunsRow, error) {
	rows, err := q.db.Query(ctx, failRunningRuns, error)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailRunningRunsRow
	for rows.Next() {
		var i FailRunningRunsRow
		if err := rows.Scan(&i.ID, &i.Steps, &i.Workspace); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findConversation = `-- name: FindConversation :one
SELECT first.id, harness_versions.workspace, harness_versions.name AS harness,
       left(first.input, 100)::text AS title
FROM runs first
JOIN harness_versions ON harness_versions.id = first.harness_version_id
WHERE first.id = $1 AND first.id = first.conversation_id
  AND first.started_by = $2
`

type FindConversationParams struct {
	ID        string
	StartedBy string
}

type FindConversationRow struct {
	ID        string
	Workspace string
	Harness   string
	Title     string
}

// The conversation named by id, if started_by started it, in any workspace.
// Its status is its latest run's, which OwnConversation reads with its runs.
func (q *Queries) FindConversation(ctx context.Context, arg FindConversationParams) (FindConversationRow, error) {
	row := q.db.QueryRow(ctx, findConversation, arg.ID, arg.StartedBy)
	var i FindConversationRow
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.Harness,
		&i.Title,
	)
	return i, err
}

const finishRun = `-- name: FinishRun :one
UPDATE runs
SET status = $2, output = $3, steps = $4, error = $5, finished_at = now()
FROM harness_versions
WHERE runs.id = $1 AND runs.status = 'running' AND harness_versions.id = runs.harness_version_id
RETURNING harness_versions.workspace
`

type FinishRunParams struct {
	ID     string
	Status string
	Output string
	Steps  int32
	Error  string
}

// The run's end, if it was running; it returns the run's workspace.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (string, error) {
	row := q.db.QueryRow(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.Steps,
		arg.Error,
	)
	var workspace string
	err := row.Scan(&workspace)
	return workspace, err
}

const getAuditRun = `-- name: GetAuditRun :one
SELECT runs.id, runs.harness_version_id, runs.input, runs.started_by, runs.conversation_id, runs.follows, runs.status, runs.output, runs.steps, runs.error, runs.prompt_digest, runs.history_digest, runs.input_tokens, runs.output_tokens, runs.cache_write_tokens, runs.cache_read_tokens, runs.created_at, runs.finished_at, harness_versions.name AS harness, harness_versions.version AS harness_version,
       harness_versions.workspace
FROM runs
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE runs.id = $1
`

type GetAuditRunRow struct {
	Run            Run
	Harness        string
	HarnessVersion int32
	Workspace      string
}

// A run of any workspace, with its workspace. For auditors only.
func (q *Queries) GetAuditRun(ctx context.Context, id string) (GetAuditRunRow, error) {
	row := q.db.QueryRow(ctx, getAuditRun, id)
	var i GetAuditRunRow
	err := row.Scan(
		&i.Run.ID,
		&i.Run.HarnessVersionID,
		&i.Run.Input,
		&i.Run.StartedBy,
		&i.Run.ConversationID,
		&i.Run.Follows,
		&i.Run.Status,
		&i.Run.Output,
		&i.Run.Steps,
		&i.Run.Error,
		&i.Run.PromptDigest,
		&i.Run.HistoryDigest,
		&i.Run.InputTokens,
		&i.Run.OutputTokens,
		&i.Run.CacheWriteTokens,
		&i.Run.CacheReadTokens,
		&i.Run.CreatedAt,
		&i.Run.FinishedAt,
		&i.Harness,
		&i.HarnessVersion,
		&i.Workspace,
	)
	return i, err
}

const getOwnRun = `-- name: GetOwnRun :one
SELECT runs.id, runs.harness_version_id, runs.input, runs.started_by, runs.conversation_id, runs.follows, runs.status, runs.output, runs.steps, runs.error, runs.prompt_digest, runs.history_digest, runs.input_tokens, runs.output_tokens, runs.cache_write_tokens, runs.cache_read_tokens, runs.created_at, runs.finished_at, harness_versions.name AS harness, harness_versions.version AS harness_version
FROM runs
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE runs.id = $1 AND harness_versions.workspace = $2
  AND runs.started_by = $3
`

type GetOwnRunParams struct {
	ID        string
	Workspace string
	Owner     string
}

type GetOwnRunRow struct {
	Run            Run
	Harness        string
	HarnessVersion int32
}

// A run of the workspace, found only for the user who started it, who
// started its conversation: only they follow it up.
func (q *Queries) GetOwnRun(ctx context.Context, arg GetOwnRunParams) (GetOwnRunRow, error) {
	row := q.db.QueryRow(ctx, getOwnRun, arg.ID, arg.Workspace, arg.Owner)
	var i GetOwnRunRow
	err := row.Scan(
		&i.Run.ID,
		&i.Run.HarnessVersionID,
		&i.Run.Input,
		&i.Run.StartedBy,
		&i.Run.ConversationID,
		&i.Run.Follows,
		&i.Run.Status,
		&i.Run.Output,
		&i.Run.Steps,
		&i.Run.Error,
		&i.Run.PromptDigest,
		&i.Run.HistoryDigest,
		&i.Run.InputTokens,
		&i.Run.OutputTokens,
		&i.Run.CacheWriteTokens,
		&i.Run.CacheReadTokens,
		&i.Run.CreatedAt,
		&i.Run.FinishedAt,
		&i.Harness,
		&i.HarnessVersion,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT runs.id, runs.harness_version_id, runs.input, runs.started_by, runs.conversation_id, runs.follows, runs.status, runs.output, runs.steps, runs.error, runs.prompt_digest, runs.history_digest, runs.input_tokens, runs.output_tokens, runs.cache_write_tokens, runs.cache_read_tokens, runs.created_at, runs.finished_at, harness_versions.name AS harness, harness_versions.version AS harness_version
FROM runs
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE runs.id = $1 AND harness_versions.workspace = $2
`

type GetRunParams struct {
	ID        string
	Workspace string
}

type GetRunRow struct {
	Run            Run
	Harness        string
	HarnessVersion int32
}

// A run is found only in the workspace of the harness version it runs.
func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.Workspace)
	var i GetRunRow
	err := row.Scan(
		&i.Run.ID,
		&i.Run.HarnessVersionID,
		&i.Run.Input,
		&i.Run.StartedBy,
		&i.Run.ConversationID,
		&i.Run.Follows,
		&i.Run.Status,
		&i.Run.Output,
		&i.Run.Steps,
		&i.Run.Error,
		&i.Run.PromptDigest,
		&i.Run.HistoryDigest,
		&i.Run.InputTokens,
		&i.Run.OutputTokens,
		&i.Run.CacheWriteTokens,
		&i.Run.CacheReadTokens,
		&i.Run.CreatedAt,
		&i.Run.FinishedAt,
		&i.Harness,
		&i.HarnessVersion,
	)
	return i, err
}

const idleRuns = `-- name: IdleRuns :many
SELECT runs.id, runs.status, harness_versions.workspace, harness_versions.name AS harness, runs.started_by AS owner
FROM runs
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE runs.status IN ('queued', 'waiting')
ORDER BY runs.created_at, runs.id
`

type IdleRunsRow struct {
	ID        string
	Status    string
	Workspace string
	Harness   string
	Owner     string
}

// The runs no worker holds that have not finished, queued or waiting, oldest
// first, with their workspaces, harnesses and the users who started them.
func (q *Queries) IdleRuns(ctx context.Context) ([]IdleRunsRow, error) {
	rows, err := q.db.Query(ctx, idleRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdleRunsRow
	for rows.Next() {
		var i IdleRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Workspace,
			&i.Harness,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (id, harness_version_id, input, started_by, conversation_id, follows)
SELECT $1::text, $2::bigint, $3::text, $4::text,
    COALESCE(f.conversation_id, $1::text), f.id
FROM (SELECT $5::text AS id) wanted
LEFT JOIN runs f ON f.id = wanted.id AND f.started_by = $4::text
WHERE wanted.id IS NULL OR f.id IS NOT NULL
RETURNING runs.id, runs.harness_version_id, runs.input, runs.started_by, runs.conversation_id, runs.follows, runs.status, runs.output, runs.steps, runs.error, runs.prompt_digest, runs.history_digest, runs.input_tokens, runs.output_tokens, runs.cache_write_tokens, runs.cache_read_tokens, runs.created_at, runs.finished_at,
    (SELECT hv.name FROM harness_versions hv WHERE hv.id = runs.harness_version_id)::text AS harness,
    (SELECT hv.version FROM harness_versions hv WHERE hv.id = runs.harness_version_id)::integer AS harness_version,
    (SELECT hv.workspace FROM harness_versions hv WHERE hv.id = runs.harness_version_id)::text AS workspace
`

type InsertRunParams struct {
	ID               string
	HarnessVersionID int64
	Input            string
	StartedBy        string
	Follows          pgtype.Text
}

type InsertRunRow struct {
	Run            Run
	Harness        string
	HarnessVersion int32
	Workspace      string
}

// A run is stored as queued. A run that follows another joins its
// conversation, and follows only a run its own starter started, so a
// conversation is one user's; any other run starts one of its own. It is
// returned as stored, before a worker may claim it, with its harness; no
// row is returned for a run that follows no run of its starter.
func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (InsertRunRow, error) {
	row := q.db.QueryRow(ctx, insertRun,
		arg.ID,
		arg.HarnessVersionID,
		arg.Input,
		arg.StartedBy,
		arg.Follows,
	)
	var i InsertRunRow
	err := row.Scan(
		&i.Run.ID,
		&i.Run.HarnessVersionID,
		&i.Run.Input,
		&i.Run.StartedBy,
		&i.Run.ConversationID,
		&i.Run.Follows,
		&i.Run.Status,
		&i.Run.Output,
		&i.Run.Steps,
		&i.Run.Error,
		&i.Run.PromptDigest,
		&i.Run.HistoryDigest,
		&i.Run.InputTokens,
		&i.Run.OutputTokens,
		&i.Run.CacheWriteTokens,
		&i.Run.CacheReadTokens,
		&i.Run.CreatedAt,
		&i.Run.FinishedAt,
		&i.Harness,
		&i.HarnessVersion,
		&i.Workspace,
	)
	return i, err
}

const listAuditRuns = `-- name: ListAuditRuns :many
SELECT runs.id, runs.harness_version_id, runs.input, runs.started_by, runs.conversation_id, runs.follows, runs.status, runs.output, runs.steps, runs.error, runs.prompt_digest, runs.history_digest, runs.input_tokens, runs.output_tokens, runs.cache_write_tokens, runs.cache_read_tokens, runs.created_at, runs.finished_at, harness_versions.name AS harness, harness_versions.version AS harness_version,
       harness_versions.workspace
FROM runs
JOIN harness_versions ON harness_versions.id = runs.harness_version_id
WHERE ($1::text IS NULL OR harness_versions.workspace = $1)
  AND ($2::text IS NULL OR harness_versions.name = $2)
  AND ($3::text IS NULL OR runs.started_by = $3)
  AND ($4::text IS NULL OR runs.status = $4)
  AND ($5::text IS NULL
       OR (runs.created_at, runs.id) < (SELECT b.created_at, b.id FROM runs b WHERE b.id = $5))
ORDER BY runs.created_at DESC, runs.id DESC
LIMIT $6
`

type ListAuditRunsParams struct {
	Workspace pgtype.Text
	Harness   pgtype.Text
	StartedBy pgtype.Text
	Status    pgtype.Text
	Before    pgtype.Text
	MaxRows   int32
}

type ListAuditRunsRow struct {
	Run            Run
	Harness        string
	HarnessVersion int32
	Workspace      string
}

// The runs of every workspace, newest first, each with its workspace,
// optionally of one workspace, harness, starter or status, starting after
// the run named by before. A before that is not a run matches nothing. For
// auditors only.
func (q *Queries) ListAuditRuns(ctx context.Context, arg ListAuditRunsParams) ([]ListAuditRunsRow, error) {
	rows, err := q.db.Query(ctx, listAuditRuns,
		arg.Workspace,
		arg.Harness,
		arg.StartedBy,
		arg.Status,
		arg.Before,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRunsRow
	for rows.Next() {
		var i ListAuditRunsRow
		if err := rows.Scan(
			&i.Run.ID,
			&i.Run.HarnessVersionID,
			&i.Run.Input,
			&i.Run.StartedBy,
			&i.Run.ConversationID,
			&i.Run.Follows,
			&i.Run.Status,
			&i.Run.Output,
			&i.Run.Steps,
			&i.Run.Error,
			&i.Run.PromptDigest,
			&i.Run.HistoryDigest,
			&i.Run.InputTokens,
			&i.Run.OutputTokens,
			&i.Run.CacheWriteTokens,
			&i.Run.CacheReadTokens,
			&i.Run.CreatedAt,
			&i.Run.FinishedAt,
			&i.Harness,
			&i.HarnessVersion,
			&i.Workspace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT first.id, harness_versions.workspace, harness_versions.name AS harness,
       left(first.input, 100)::text AS title, latest.status, latest.created_at AS updated_at
FROM runs first
JOIN harness_versions ON harness_versions.id = first.harness_version_id
JOIN runs latest ON latest.conversation_id = first.id
 AND NOT EXISTS (SELECT 1 FROM runs n WHERE n.follows = latest.id)
WHERE first.id = first.conversation_id
  AND first.started_by = $1
  AND ($2::text IS NULL
       OR (latest.created_at, first.id) < ($3::timestamptz, $2::text))
ORDER BY latest.created_at DESC, first.id DESC
LIMIT $4
`

type ListConversationsParams struct {
	StartedBy string
	BeforeID  pgtype.Text
	BeforeAt  *time.Time
	MaxRows   int32
}

type ListConversationsRow struct {
	ID        string
	Workspace string
	Harness   string
	Title     string
	Status    string
	UpdatedAt time.Time
}

// The conversations started_by started, in any workspace, latest activity
// first, after the one with before_at and before_id when they are
// set. A conversation is its first run, whose ID names it, and its latest
// run, the one no run follows, whose creation is its latest activity.
func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations,
		arg.StartedBy,
		arg.BeforeID,
		arg.BeforeAt,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Workspace,
			&i.Harness,
			&i.Title,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollbackToClosing = `-- name: RollbackToClosing :exec
ROLLBACK TO SAVEPOINT closing
`

func (q *Queries) RollbackToClosing(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rollbackToClosing)
	return err
}

const savepointClosing = `-- name: SavepointClosing :exec
SAVEPOINT closing
`

// What a cancelled run did not do is stored after this savepoint, so the
// cancel can go ahead without it.
func (q *Queries) SavepointClosing(ctx context.Context) error {
	_, err := q.db.Exec(ctx, savepointClosing)
	return err
}

const setRunDigests = `-- name: SetRunDigests :execrows
UPDATE runs
SET prompt_digest = $2, history_digest = $3
WHERE id = $1 AND status = 'running'
`

type SetRunDigestsParams struct {
	ID            string
	PromptDigest  string
	HistoryDigest string
}

func (q *Queries) SetRunDigests(ctx context.Context, arg SetRunDigestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunDigests, arg.ID, arg.PromptDigest, arg.HistoryDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
