// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript.sql

package db

import (
	"context"
)

const insertRunMessage = `-- name: InsertRunMessage :exec
WITH message AS (
    INSERT INTO run_messages (
        run_id, position, role, text, tool_calls, tool_results, provider, provider_data, altered,
        input_tokens, output_tokens, cache_write_tokens, cache_read_tokens
    )
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
    RETURNING run_id, input_tokens, output_tokens, cache_write_tokens, cache_read_tokens
)
UPDATE runs
SET input_tokens       = runs.input_tokens + message.input_tokens,
    output_tokens      = runs.output_tokens + message.output_tokens,
    cache_write_tokens = runs.cache_write_tokens + message.cache_write_tokens,
    cache_read_tokens  = runs.cache_read_tokens + message.cache_read_tokens
FROM message
WHERE runs.id = message.run_id
`

type InsertRunMessageParams struct {
	RunID            string
	Position         int32
	Role             string
	Text             string
	ToolCalls        []byte
	ToolResults      []byte
	Provider         string
	ProviderData     []byte
	Altered          bool
	InputTokens      int64
	OutputTokens     int64
	CacheWriteTokens int64
	CacheReadTokens  int64
}

// Stores a message and adds its tokens to its run's. One statement does
// both, so a run's totals always equal the sum of its stored messages. The
// primary key refuses a position written before, and the foreign key a run
// that is not stored.
func (q *Queries) InsertRunMessage(ctx context.Context, arg InsertRunMessageParams) error {
	_, err := q.db.Exec(ctx, insertRunMessage,
		arg.RunID,
		arg.Position,
		arg.Role,
		arg.Text,
		arg.ToolCalls,
		arg.ToolResults,
		arg.Provider,
		arg.ProviderData,
		arg.Altered,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheWriteTokens,
		arg.CacheReadTokens,
	)
	return err
}

const runMessages = `-- name: RunMessages :many
SELECT run_id, position, role, text, tool_calls, tool_results, provider, provider_data, altered, input_tokens, output_tokens, cache_write_tokens, cache_read_tokens, created_at FROM run_messages
WHERE run_id = $1
ORDER BY position
`

// A run's transcript in order. A run without messages, or one that does not
// exist, has none.
func (q *Queries) RunMessages(ctx context.Context, runID string) ([]RunMessage, error) {
	rows, err := q.db.Query(ctx, runMessages, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunMessage
	for rows.Next() {
		var i RunMessage
		if err := rows.Scan(
			&i.RunID,
			&i.Position,
			&i.Role,
			&i.Text,
			&i.ToolCalls,
			&i.ToolResults,
			&i.Provider,
			&i.ProviderData,
			&i.Altered,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheReadTokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
