// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript.sql

package db

import (
	"context"
)

const insertRunMessage = `-- name: InsertRunMessage :exec
INSERT INTO run_messages (run_id, position, role, text, tool_calls, tool_results)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRunMessageParams struct {
	RunID       string
	Position    int32
	Role        string
	Text        string
	ToolCalls   []byte
	ToolResults []byte
}

func (q *Queries) InsertRunMessage(ctx context.Context, arg InsertRunMessageParams) error {
	_, err := q.db.Exec(ctx, insertRunMessage,
		arg.RunID,
		arg.Position,
		arg.Role,
		arg.Text,
		arg.ToolCalls,
		arg.ToolResults,
	)
	return err
}

const runMessages = `-- name: RunMessages :many
SELECT run_id, position, role, text, tool_calls, tool_results, created_at FROM run_messages
WHERE run_id = $1
ORDER BY position
`

func (q *Queries) RunMessages(ctx context.Context, runID string) ([]RunMessage, error) {
	rows, err := q.db.Query(ctx, runMessages, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunMessage
	for rows.Next() {
		var i RunMessage
		if err := rows.Scan(
			&i.RunID,
			&i.Position,
			&i.Role,
			&i.Text,
			&i.ToolCalls,
			&i.ToolResults,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
