/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedActivityRouteImport } from './routes/_authed/activity'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedAuditIndexRouteImport } from './routes/_authed/audit/index'
import { Route as AuthedAuditEventsRouteImport } from './routes/_authed/audit/events'
import { Route as AuthedCConversationIdRouteImport } from './routes/_authed/c.$conversationId'
import { Route as AuthedWWorkspaceRouteImport } from './routes/_authed/w/$workspace'
import { Route as AuthedAuditRunsRunIdRouteImport } from './routes/_authed/audit/runs.$runId'
import { Route as AuthedWWorkspaceIndexRouteImport } from './routes/_authed/w/$workspace/index'
import { Route as AuthedWWorkspaceAuditRouteImport } from './routes/_authed/w/$workspace/audit'
import { Route as AuthedWWorkspaceNewHarnessRouteImport } from './routes/_authed/w/$workspace/new-harness'
import { Route as AuthedWWorkspaceHarnessesIndexRouteImport } from './routes/_authed/w/$workspace/harnesses/index'
import { Route as AuthedWWorkspaceHarnessesNameRouteRouteImport } from './routes/_authed/w/$workspace/harnesses/$name/route'
import { Route as AuthedWWorkspaceHarnessesNameIndexRouteImport } from './routes/_authed/w/$workspace/harnesses/$name/index'
import { Route as AuthedWWorkspaceHarnessesNameEditRouteImport } from './routes/_authed/w/$workspace/harnesses/$name/edit'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditIndexRoute = AuthedAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAuditRoute,
} as any)
const AuthedAuditEventsRoute = AuthedAuditEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthedAuditRoute,
} as any)
const AuthedCConversationIdRoute = AuthedCConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWWorkspaceRoute = AuthedWWorkspaceRouteImport.update({
  id: '/w/$workspace',
  path: '/w/$workspace',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRunsRunIdRoute = AuthedAuditRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthedAuditRoute,
} as any)
const AuthedWWorkspaceIndexRoute = AuthedWWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWWorkspaceRoute,
} as any)
const AuthedWWorkspaceAuditRoute = AuthedWWorkspaceAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedWWorkspaceRoute,
} as any)
const AuthedWWorkspaceNewHarnessRoute =
  AuthedWWorkspaceNewHarnessRouteImport.update({
    id: '/new-harness',
    path: '/new-harness',
    getParentRoute: () => AuthedWWorkspaceRoute,
  } as any)
const AuthedWWorkspaceHarnessesIndexRoute =
  AuthedWWorkspaceHarnessesIndexRouteImport.update({
    id: '/harnesses/',
    path: '/harnesses/',
    getParentRoute: () => AuthedWWorkspaceRoute,
  } as any)
const AuthedWWorkspaceHarnessesNameRouteRoute =
  AuthedWWorkspaceHarnessesNameRouteRouteImport.update({
    id: '/harnesses/$name',
    path: '/harnesses/$name',
    getParentRoute: () => AuthedWWorkspaceRoute,
  } as any)
const AuthedWWorkspaceHarnessesNameIndexRoute =
  AuthedWWorkspaceHarnessesNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWWorkspaceHarnessesNameRouteRoute,
  } as any)
const AuthedWWorkspaceHarnessesNameEditRoute =
  AuthedWWorkspaceHarnessesNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedWWorkspaceHarnessesNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/activity': typeof AuthedActivityRoute
  '/audit': typeof AuthedAuditRouteWithChildren
  '/audit/events': typeof AuthedAuditEventsRoute
  '/c/$conversationId': typeof AuthedCConversationIdRoute
  '/w/$workspace': typeof AuthedWWorkspaceRouteWithChildren
  '/audit/': typeof AuthedAuditIndexRoute
  '/audit/runs/$runId': typeof AuthedAuditRunsRunIdRoute
  '/w/$workspace/audit': typeof AuthedWWorkspaceAuditRoute
  '/w/$workspace/new-harness': typeof AuthedWWorkspaceNewHarnessRoute
  '/w/$workspace/': typeof AuthedWWorkspaceIndexRoute
  '/w/$workspace/harnesses/$name': typeof AuthedWWorkspaceHarnessesNameRouteRouteWithChildren
  '/w/$workspace/harnesses/': typeof AuthedWWorkspaceHarnessesIndexRoute
  '/w/$workspace/harnesses/$name/edit': typeof AuthedWWorkspaceHarnessesNameEditRoute
  '/w/$workspace/harnesses/$name/': typeof AuthedWWorkspaceHarnessesNameIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/activity': typeof AuthedActivityRoute
  '/': typeof AuthedIndexRoute
  '/audit/events': typeof AuthedAuditEventsRoute
  '/c/$conversationId': typeof AuthedCConversationIdRoute
  '/audit': typeof AuthedAuditIndexRoute
  '/audit/runs/$runId': typeof AuthedAuditRunsRunIdRoute
  '/w/$workspace/audit': typeof AuthedWWorkspaceAuditRoute
  '/w/$workspace/new-harness': typeof AuthedWWorkspaceNewHarnessRoute
  '/w/$workspace': typeof AuthedWWorkspaceIndexRoute
  '/w/$workspace/harnesses': typeof AuthedWWorkspaceHarnessesIndexRoute
  '/w/$workspace/harnesses/$name/edit': typeof AuthedWWorkspaceHarnessesNameEditRoute
  '/w/$workspace/harnesses/$name': typeof AuthedWWorkspaceHarnessesNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/audit': typeof AuthedAuditRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/audit/events': typeof AuthedAuditEventsRoute
  '/_authed/c/$conversationId': typeof AuthedCConversationIdRoute
  '/_authed/w/$workspace': typeof AuthedWWorkspaceRouteWithChildren
  '/_authed/audit/': typeof AuthedAuditIndexRoute
  '/_authed/audit/runs/$runId': typeof AuthedAuditRunsRunIdRoute
  '/_authed/w/$workspace/audit': typeof AuthedWWorkspaceAuditRoute
  '/_authed/w/$workspace/new-harness': typeof AuthedWWorkspaceNewHarnessRoute
  '/_authed/w/$workspace/': typeof AuthedWWorkspaceIndexRoute
  '/_authed/w/$workspace/harnesses/$name': typeof AuthedWWorkspaceHarnessesNameRouteRouteWithChildren
  '/_authed/w/$workspace/harnesses/': typeof AuthedWWorkspaceHarnessesIndexRoute
  '/_authed/w/$workspace/harnesses/$name/edit': typeof AuthedWWorkspaceHarnessesNameEditRoute
  '/_authed/w/$workspace/harnesses/$name/': typeof AuthedWWorkspaceHarnessesNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/activity'
    | '/audit'
    | '/audit/events'
    | '/c/$conversationId'
    | '/w/$workspace'
    | '/audit/'
    | '/audit/runs/$runId'
    | '/w/$workspace/audit'
    | '/w/$workspace/new-harness'
    | '/w/$workspace/'
    | '/w/$workspace/harnesses/$name'
    | '/w/$workspace/harnesses/'
    | '/w/$workspace/harnesses/$name/edit'
    | '/w/$workspace/harnesses/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/activity'
    | '/'
    | '/audit/events'
    | '/c/$conversationId'
    | '/audit'
    | '/audit/runs/$runId'
    | '/w/$workspace/audit'
    | '/w/$workspace/new-harness'
    | '/w/$workspace'
    | '/w/$workspace/harnesses'
    | '/w/$workspace/harnesses/$name/edit'
    | '/w/$workspace/harnesses/$name'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/activity'
    | '/_authed/audit'
    | '/_authed/'
    | '/_authed/audit/events'
    | '/_authed/c/$conversationId'
    | '/_authed/w/$workspace'
    | '/_authed/audit/'
    | '/_authed/audit/runs/$runId'
    | '/_authed/w/$workspace/audit'
    | '/_authed/w/$workspace/new-harness'
    | '/_authed/w/$workspace/'
    | '/_authed/w/$workspace/harnesses/$name'
    | '/_authed/w/$workspace/harnesses/'
    | '/_authed/w/$workspace/harnesses/$name/edit'
    | '/_authed/w/$workspace/harnesses/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit/': {
      id: '/_authed/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthedAuditIndexRouteImport
      parentRoute: typeof AuthedAuditRoute
    }
    '/_authed/audit/events': {
      id: '/_authed/audit/events'
      path: '/events'
      fullPath: '/audit/events'
      preLoaderRoute: typeof AuthedAuditEventsRouteImport
      parentRoute: typeof AuthedAuditRoute
    }
    '/_authed/c/$conversationId': {
      id: '/_authed/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof AuthedCConversationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/w/$workspace': {
      id: '/_authed/w/$workspace'
      path: '/w/$workspace'
      fullPath: '/w/$workspace'
      preLoaderRoute: typeof AuthedWWorkspaceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit/runs/$runId': {
      id: '/_authed/audit/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/audit/runs/$runId'
      preLoaderRoute: typeof AuthedAuditRunsRunIdRouteImport
      parentRoute: typeof AuthedAuditRoute
    }
    '/_authed/w/$workspace/': {
      id: '/_authed/w/$workspace/'
      path: '/'
      fullPath: '/w/$workspace/'
      preLoaderRoute: typeof AuthedWWorkspaceIndexRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/audit': {
      id: '/_authed/w/$workspace/audit'
      path: '/audit'
      fullPath: '/w/$workspace/audit'
      preLoaderRoute: typeof AuthedWWorkspaceAuditRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/new-harness': {
      id: '/_authed/w/$workspace/new-harness'
      path: '/new-harness'
      fullPath: '/w/$workspace/new-harness'
      preLoaderRoute: typeof AuthedWWorkspaceNewHarnessRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/harnesses/': {
      id: '/_authed/w/$workspace/harnesses/'
      path: '/harnesses'
      fullPath: '/w/$workspace/harnesses/'
      preLoaderRoute: typeof AuthedWWorkspaceHarnessesIndexRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/harnesses/$name': {
      id: '/_authed/w/$workspace/harnesses/$name'
      path: '/harnesses/$name'
      fullPath: '/w/$workspace/harnesses/$name'
      preLoaderRoute: typeof AuthedWWorkspaceHarnessesNameRouteRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/harnesses/$name/': {
      id: '/_authed/w/$workspace/harnesses/$name/'
      path: '/'
      fullPath: '/w/$workspace/harnesses/$name/'
      preLoaderRoute: typeof AuthedWWorkspaceHarnessesNameIndexRouteImport
      parentRoute: typeof AuthedWWorkspaceHarnessesNameRouteRoute
    }
    '/_authed/w/$workspace/harnesses/$name/edit': {
      id: '/_authed/w/$workspace/harnesses/$name/edit'
      path: '/edit'
      fullPath: '/w/$workspace/harnesses/$name/edit'
      preLoaderRoute: typeof AuthedWWorkspaceHarnessesNameEditRouteImport
      parentRoute: typeof AuthedWWorkspaceHarnessesNameRouteRoute
    }
  }
}

interface AuthedAuditRouteChildren {
  AuthedAuditEventsRoute: typeof AuthedAuditEventsRoute
  AuthedAuditIndexRoute: typeof AuthedAuditIndexRoute
  AuthedAuditRunsRunIdRoute: typeof AuthedAuditRunsRunIdRoute
}

const AuthedAuditRouteChildren: AuthedAuditRouteChildren = {
  AuthedAuditEventsRoute: AuthedAuditEventsRoute,
  AuthedAuditIndexRoute: AuthedAuditIndexRoute,
  AuthedAuditRunsRunIdRoute: AuthedAuditRunsRunIdRoute,
}

const AuthedAuditRouteWithChildren = AuthedAuditRoute._addFileChildren(
  AuthedAuditRouteChildren,
)

interface AuthedWWorkspaceHarnessesNameRouteRouteChildren {
  AuthedWWorkspaceHarnessesNameEditRoute: typeof AuthedWWorkspaceHarnessesNameEditRoute
  AuthedWWorkspaceHarnessesNameIndexRoute: typeof AuthedWWorkspaceHarnessesNameIndexRoute
}

const AuthedWWorkspaceHarnessesNameRouteRouteChildren: AuthedWWorkspaceHarnessesNameRouteRouteChildren =
  {
    AuthedWWorkspaceHarnessesNameEditRoute:
      AuthedWWorkspaceHarnessesNameEditRoute,
    AuthedWWorkspaceHarnessesNameIndexRoute:
      AuthedWWorkspaceHarnessesNameIndexRoute,
  }

const AuthedWWorkspaceHarnessesNameRouteRouteWithChildren =
  AuthedWWorkspaceHarnessesNameRouteRoute._addFileChildren(
    AuthedWWorkspaceHarnessesNameRouteRouteChildren,
  )

interface AuthedWWorkspaceRouteChildren {
  AuthedWWorkspaceAuditRoute: typeof AuthedWWorkspaceAuditRoute
  AuthedWWorkspaceNewHarnessRoute: typeof AuthedWWorkspaceNewHarnessRoute
  AuthedWWorkspaceIndexRoute: typeof AuthedWWorkspaceIndexRoute
  AuthedWWorkspaceHarnessesNameRouteRoute: typeof AuthedWWorkspaceHarnessesNameRouteRouteWithChildren
  AuthedWWorkspaceHarnessesIndexRoute: typeof AuthedWWorkspaceHarnessesIndexRoute
}

const AuthedWWorkspaceRouteChildren: AuthedWWorkspaceRouteChildren = {
  AuthedWWorkspaceAuditRoute: AuthedWWorkspaceAuditRoute,
  AuthedWWorkspaceNewHarnessRoute: AuthedWWorkspaceNewHarnessRoute,
  AuthedWWorkspaceIndexRoute: AuthedWWorkspaceIndexRoute,
  AuthedWWorkspaceHarnessesNameRouteRoute:
    AuthedWWorkspaceHarnessesNameRouteRouteWithChildren,
  AuthedWWorkspaceHarnessesIndexRoute: AuthedWWorkspaceHarnessesIndexRoute,
}

const AuthedWWorkspaceRouteWithChildren =
  AuthedWWorkspaceRoute._addFileChildren(AuthedWWorkspaceRouteChildren)

interface AuthedRouteChildren {
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedAuditRoute: typeof AuthedAuditRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCConversationIdRoute: typeof AuthedCConversationIdRoute
  AuthedWWorkspaceRoute: typeof AuthedWWorkspaceRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedAuditRoute: AuthedAuditRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCConversationIdRoute: AuthedCConversationIdRoute,
  AuthedWWorkspaceRoute: AuthedWWorkspaceRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
