/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedWWorkspaceRouteImport } from './routes/_authed/w/$workspace'
import { Route as AuthedWWorkspaceIndexRouteImport } from './routes/_authed/w/$workspace/index'
import { Route as AuthedWWorkspaceApprovalsRouteImport } from './routes/_authed/w/$workspace/approvals'
import { Route as AuthedWWorkspaceHarnessesIndexRouteImport } from './routes/_authed/w/$workspace/harnesses/index'
import { Route as AuthedWWorkspaceHarnessesNameRouteImport } from './routes/_authed/w/$workspace/harnesses/$name'
import { Route as AuthedWWorkspaceRunsIndexRouteImport } from './routes/_authed/w/$workspace/runs/index'
import { Route as AuthedWWorkspaceRunsRunIdRouteImport } from './routes/_authed/w/$workspace/runs/$runId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWWorkspaceRoute = AuthedWWorkspaceRouteImport.update({
  id: '/w/$workspace',
  path: '/w/$workspace',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWWorkspaceIndexRoute = AuthedWWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWWorkspaceRoute,
} as any)
const AuthedWWorkspaceApprovalsRoute =
  AuthedWWorkspaceApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthedWWorkspaceRoute,
  } as any)
const AuthedWWorkspaceHarnessesIndexRoute =
  AuthedWWorkspaceHarnessesIndexRouteImport.update({
    id: '/harnesses/',
    path: '/harnesses/',
    getParentRoute: () => AuthedWWorkspaceRoute,
  } as any)
const AuthedWWorkspaceHarnessesNameRoute =
  AuthedWWorkspaceHarnessesNameRouteImport.update({
    id: '/harnesses/$name',
    path: '/harnesses/$name',
    getParentRoute: () => AuthedWWorkspaceRoute,
  } as any)
const AuthedWWorkspaceRunsIndexRoute =
  AuthedWWorkspaceRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AuthedWWorkspaceRoute,
  } as any)
const AuthedWWorkspaceRunsRunIdRoute =
  AuthedWWorkspaceRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => AuthedWWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/w/$workspace': typeof AuthedWWorkspaceRouteWithChildren
  '/w/$workspace/approvals': typeof AuthedWWorkspaceApprovalsRoute
  '/w/$workspace/': typeof AuthedWWorkspaceIndexRoute
  '/w/$workspace/harnesses/$name': typeof AuthedWWorkspaceHarnessesNameRoute
  '/w/$workspace/runs/$runId': typeof AuthedWWorkspaceRunsRunIdRoute
  '/w/$workspace/harnesses/': typeof AuthedWWorkspaceHarnessesIndexRoute
  '/w/$workspace/runs/': typeof AuthedWWorkspaceRunsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof AuthedIndexRoute
  '/w/$workspace/approvals': typeof AuthedWWorkspaceApprovalsRoute
  '/w/$workspace': typeof AuthedWWorkspaceIndexRoute
  '/w/$workspace/harnesses/$name': typeof AuthedWWorkspaceHarnessesNameRoute
  '/w/$workspace/runs/$runId': typeof AuthedWWorkspaceRunsRunIdRoute
  '/w/$workspace/harnesses': typeof AuthedWWorkspaceHarnessesIndexRoute
  '/w/$workspace/runs': typeof AuthedWWorkspaceRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/w/$workspace': typeof AuthedWWorkspaceRouteWithChildren
  '/_authed/w/$workspace/approvals': typeof AuthedWWorkspaceApprovalsRoute
  '/_authed/w/$workspace/': typeof AuthedWWorkspaceIndexRoute
  '/_authed/w/$workspace/harnesses/$name': typeof AuthedWWorkspaceHarnessesNameRoute
  '/_authed/w/$workspace/runs/$runId': typeof AuthedWWorkspaceRunsRunIdRoute
  '/_authed/w/$workspace/harnesses/': typeof AuthedWWorkspaceHarnessesIndexRoute
  '/_authed/w/$workspace/runs/': typeof AuthedWWorkspaceRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/w/$workspace'
    | '/w/$workspace/approvals'
    | '/w/$workspace/'
    | '/w/$workspace/harnesses/$name'
    | '/w/$workspace/runs/$runId'
    | '/w/$workspace/harnesses/'
    | '/w/$workspace/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/w/$workspace/approvals'
    | '/w/$workspace'
    | '/w/$workspace/harnesses/$name'
    | '/w/$workspace/runs/$runId'
    | '/w/$workspace/harnesses'
    | '/w/$workspace/runs'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/'
    | '/_authed/w/$workspace'
    | '/_authed/w/$workspace/approvals'
    | '/_authed/w/$workspace/'
    | '/_authed/w/$workspace/harnesses/$name'
    | '/_authed/w/$workspace/runs/$runId'
    | '/_authed/w/$workspace/harnesses/'
    | '/_authed/w/$workspace/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/w/$workspace': {
      id: '/_authed/w/$workspace'
      path: '/w/$workspace'
      fullPath: '/w/$workspace'
      preLoaderRoute: typeof AuthedWWorkspaceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/w/$workspace/': {
      id: '/_authed/w/$workspace/'
      path: '/'
      fullPath: '/w/$workspace/'
      preLoaderRoute: typeof AuthedWWorkspaceIndexRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/approvals': {
      id: '/_authed/w/$workspace/approvals'
      path: '/approvals'
      fullPath: '/w/$workspace/approvals'
      preLoaderRoute: typeof AuthedWWorkspaceApprovalsRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/harnesses/': {
      id: '/_authed/w/$workspace/harnesses/'
      path: '/harnesses'
      fullPath: '/w/$workspace/harnesses/'
      preLoaderRoute: typeof AuthedWWorkspaceHarnessesIndexRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/harnesses/$name': {
      id: '/_authed/w/$workspace/harnesses/$name'
      path: '/harnesses/$name'
      fullPath: '/w/$workspace/harnesses/$name'
      preLoaderRoute: typeof AuthedWWorkspaceHarnessesNameRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/runs/': {
      id: '/_authed/w/$workspace/runs/'
      path: '/runs'
      fullPath: '/w/$workspace/runs/'
      preLoaderRoute: typeof AuthedWWorkspaceRunsIndexRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/runs/$runId': {
      id: '/_authed/w/$workspace/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/w/$workspace/runs/$runId'
      preLoaderRoute: typeof AuthedWWorkspaceRunsRunIdRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
  }
}

interface AuthedWWorkspaceRouteChildren {
  AuthedWWorkspaceApprovalsRoute: typeof AuthedWWorkspaceApprovalsRoute
  AuthedWWorkspaceIndexRoute: typeof AuthedWWorkspaceIndexRoute
  AuthedWWorkspaceHarnessesNameRoute: typeof AuthedWWorkspaceHarnessesNameRoute
  AuthedWWorkspaceRunsRunIdRoute: typeof AuthedWWorkspaceRunsRunIdRoute
  AuthedWWorkspaceHarnessesIndexRoute: typeof AuthedWWorkspaceHarnessesIndexRoute
  AuthedWWorkspaceRunsIndexRoute: typeof AuthedWWorkspaceRunsIndexRoute
}

const AuthedWWorkspaceRouteChildren: AuthedWWorkspaceRouteChildren = {
  AuthedWWorkspaceApprovalsRoute: AuthedWWorkspaceApprovalsRoute,
  AuthedWWorkspaceIndexRoute: AuthedWWorkspaceIndexRoute,
  AuthedWWorkspaceHarnessesNameRoute: AuthedWWorkspaceHarnessesNameRoute,
  AuthedWWorkspaceRunsRunIdRoute: AuthedWWorkspaceRunsRunIdRoute,
  AuthedWWorkspaceHarnessesIndexRoute: AuthedWWorkspaceHarnessesIndexRoute,
  AuthedWWorkspaceRunsIndexRoute: AuthedWWorkspaceRunsIndexRoute,
}

const AuthedWWorkspaceRouteWithChildren =
  AuthedWWorkspaceRoute._addFileChildren(AuthedWWorkspaceRouteChildren)

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedWWorkspaceRoute: typeof AuthedWWorkspaceRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedWWorkspaceRoute: AuthedWWorkspaceRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
