package dbgen_test

// The code in this package is generated by sqlc (task generate); this file is
// not. Queries run against PostgreSQL in the module tests of the database
// package; these tests cover the generated plumbing with a fake connection.

import (
	"context"
	"errors"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/jangraefen/agenty/server/internal/database/dbgen"
)

type fakeRow struct {
	value int32
	err   error
}

func (r fakeRow) Scan(dest ...any) error {
	if r.err != nil {
		return r.err
	}
	*dest[0].(*int32) = r.value
	return nil
}

type fakeDB struct {
	row   fakeRow
	query string
}

func (f *fakeDB) Exec(context.Context, string, ...any) (pgconn.CommandTag, error) {
	return pgconn.CommandTag{}, errors.New("unexpected Exec")
}

func (f *fakeDB) Query(context.Context, string, ...any) (pgx.Rows, error) {
	return nil, errors.New("unexpected Query")
}

func (f *fakeDB) QueryRow(_ context.Context, sql string, _ ...any) pgx.Row {
	f.query = sql
	return f.row
}

func TestPingScansTheResult(t *testing.T) {
	db := &fakeDB{row: fakeRow{value: 1}}

	got, err := dbgen.New(db).Ping(t.Context())

	require.NoError(t, err, "Ping")
	assert.Equal(t, int32(1), got, "result")
	assert.Contains(t, db.query, "SELECT 1", "query")
}

func TestPingReturnsTheError(t *testing.T) {
	db := &fakeDB{row: fakeRow{err: errors.New("connection refused")}}

	_, err := dbgen.New(db).Ping(t.Context())

	assert.ErrorContains(t, err, "connection refused")
}

func TestWithTxReturnsQueriesBoundToTheTransaction(t *testing.T) {
	q := dbgen.New(&fakeDB{})

	assert.NotSame(t, q, q.WithTx(nil), "WithTx must return new Queries")
}
