// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package dbgen

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::integer AS ok
`

// Ping proves that a pooled connection can run a query.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
